### ISSUE TITLE
Implement special functions

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#102]
There are lots of implementations online. 

As an example, here are the special functions that I needed in my projects over the past 10 years:

https://github.com/certik/fortran-utils/blob/b43bd24cd421509a5bc6d3b9c3eeae8ce856ed88/src/special.f90

https://github.com/certik/hfsolver/blob/b4c50c1979fb7e468b1852b144ba756f5a51788d/src/special_functions.f90

Being able to standardize on the API for all or most of them would be a huge deal. Other languages:

### SciPy

https://docs.scipy.org/doc/scipy/reference/special.html

### Matlab

https://www.mathworks.com/help/matlab/special-functions-1.html

### Julia

Separate package: [SpecialFunctions.jl](https://github.com/JuliaMath/SpecialFunctions.jl)

**Comment by 14NGiestas** [comment]
Closing it in favor of #305
