### ISSUE TITLE
Create a Fortran webpage

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#110]
We should have a dedicated repository just for the https://fortran-lang.org/ webpage. For now let's discuss here.

Here are some sections that I think should be part of it. There can be other sections too of course.

### Fortran Ecosystem Page

A curated page about the Fortran ecosystem. Here is one idea how it can look like:

https://maulingmonkey.com/guide/cpp-vs-rust/#crates-of-note

It would be automatically generated from a list of projects / metadata that we provide. A good start for a list of projects would be: https://github.com/fortran-lang/stdlib/wiki/List-of-popular-open-source-Fortran-projects (#28). We would list them by category, e.g.:

* applications (electronic structure, mechanics, ...)
* basic libraries (like stdlib)
* file io (hdf5, netcdf, ...)

The idea would be for people new to Fortran to help them discover packages and to see what the status of the Fortran ecosystem is (I really like the automatic stats like number of stars, number of commits per year, number of contributors, ...).

We can set some minimal barrier of entry to prevent spam / pet projects. In the above wiki we arbitrarily set it at 30 stars at GitHub. We can lower it to 20 or even just 10 stars or something like that.

### Fortran tutorial and reference

We can adapt what is at https://www.fortran90.org/ and other such pages, and then improving it as a community. We should also prominently list `stdlib` there.

### Compilers

It would list all the Fortran compilers, with links to their webpages, etc. Both commercial and open source. We would maintain a testsuite that the compiler needs to pass in order to be listed. It can be as simple as the reference Lapack plus a simple test program in the Fortran 90 style. So it would be a low barrier, but high enough so that the compiler is usable.

### Community

Here is an example how such a page could look like and what information to list: https://www.rust-lang.org/community

We should have some forum where anything can be discussed. Right now we are organizing the Fortran community around the two repositories:

https://github.com/fortran-lang/stdlib
https://github.com/j3-fortran/fortran_proposals

But what if somebody wants to create some meetup or a Fortran conference, or just organize some hackathon, or other things, then it would be nice to have some forum where such things can be organized. Also for announcing new Fortran projects and libraries.

Essentially this would be a place to go if you want to see what is happening in Fortran.

**Comment by milancurcic** [comment]
Fantastic! I agree this is a must have for the future of Fortran. Currently Fortran doesn't have a home on the internet. 

What should be our first step? I suggest starting with a basic landing page, and take it from there.

Examples for inspiration:

* https://clojure.org/
* https://common-lisp.net/
* https://crystal-lang.org/
* https://dlang.org/
* https://elixir-lang.org/
* https://elm-lang.org/
* https://www.erlang.org/
* https://fsharp.org/
* https://golang.org/
* https://www.haskell.org/
* https://nim-lang.org/
* https://www.python.org/
* https://racket-lang.org/
* https://www.ruby-lang.org/
* https://www.rust-lang.org/
* https://ziglang.org/

Of the bunch, I like Nim's website the best. I think the Fortran language page should say what Fortran is, describe the features of the language in brief notes (statically-typed, parallel, high performance etc.), and show an example code snippet upfront.

The landing page can lead to other pages that @certik described, and others.

**Comment by ivan-pi** [comment]
This is a great idea! It would also be helpful to have a website like https://en.cppreference.com/w/cpp. The closest thing currently as far as a simple language reference goes are the gfortran and Intel Fortran compiler pages. An online webpage with content similar to Modern Fortran Explained by Metcalf and Cohen would go a long way.

> But what if somebody wants to create some meetup or a Fortran conference, or just organize some hackathon, or other things, then it would be nice to have some forum where such things can be organized. Also for announcing new Fortran projects and libraries.

I see a lot of potential in engaging with existing Fortran users. Last year I created a Fortran group over the meetup app: https://www.meetup.com/Fortran-User-Group-Munchen/
It attracted 20 users in under a week. I have yet to organize a meetup in real life. 
(For perspective, the C++ meetup group in Munich has just under 3000 members and c. 150 users come to a typical meetup.)

**Comment by urbanjost** [comment]
As a first step would using this site and GitHub Pages suffice?  There are limits on the amount of data that Github allows to be exported as HTML and traffic limits but everything could be at one site and a skeleton could be up in a few minutes.  Seems like there is a significant advantage to starting that way as github is already set up as a collaborative site. Then you could mirror it to a "real" webpage. The Fortran Wiki is also somewhere everyone could build the content collaboratively that already exists.

**Comment by milancurcic** [comment]
This is resolved. Direct any further issues to https://github.com/fortran-lang/fortran-lang.org.

**Comment by certik** [comment]
Well, I think we have implemented all of my ideas, so we can close this issue and improve things as we go. Thanks @milancurcic, @LKedward and others to make it happen.
