### ISSUE TITLE
Classification of the issues?

### ISSUE THREAD

**Issue by jvdp1** [fortran-lang/stdlib#111]
There are now several open issues related to many topics. Several of them are related to a same scope. Would it be worthwhile to create some labels to classify a bit the issues? For example, the labels `utilities`, `algorithms` and `mathematics` (as the [scope](https://github.com/fortran-lang/stdlib#scope) of `stdlib`)?

**Comment by certik** [comment]
I think that's a great idea. Why don't you go ahead and create labels and start labeling the issues.

**Comment by milancurcic** [comment]
Thanks @jvdp1. While you're at it, can you also create the labels for the 5 steps of development from #5? That way we can also track progress for various modules/procedures.

**Comment by milancurcic** [comment]
Sorry I mean from the WORKFLOW.md.

**Comment by jvdp1** [comment]
@milancurcic I created the 5 labels `idea`, `API`, `specification`, `implementation` and `release`.

I also created labels `utilities`, `mathematics`, `algorithms`, and `compilers`, and attributed them to some of the issues.
