### ISSUE TITLE
Adding the preprocessor to the repository?

### ISSUE THREAD

**Issue by aradi** [fortran-lang/stdlib#133]
Any views on adding the pre-processor to stdlib? Fypp consists of a single file. If we had it in the repository, the build requirement would reduce to:

- Fortran compiler
- CMake
- Python

All those are quite common, while having Fypp installed on your machine rather not.

**Comment by leonfoks** [comment]
If the decision is made to omit the expanded code from the repo, this would be ideal!  It would certainly make it easier on the user.

**Comment by certik** [comment]
It's this file: https://github.com/aradi/fypp/blob/7895a7efb7d2f07dc284cece6cc9474297b8dc55/bin/fypp. 

I think that might be fine, to make it easier for people to build.

**Comment by milancurcic** [comment]
I agree this would ease development. How do you suggest to include it? Commit the script to the repo directly or as a git submodule? The latter would make keeping up to date with upstream easier.

**Comment by certik** [comment]
I would suggest to commit into the repo directly. The submodules seem to cause more trouble than benefits from my experience.

**Comment by jvdp1** [comment]
> I would suggest to commit into the repo directly. The submodules seem to cause more trouble than benefits from my experience.

What kind of troubles did you get with submodules?

**Comment by certik** [comment]
> What kind of troubles did you get with submodules?

You have to remember to clone with `--recursive`, you have to remember how to update, new users have to learn what to do when "git diff" says "dirty", and `git clean -dfx` does not clean submodules, etc. If possible, I try to avoid them.

**Comment by jvdp1** [comment]
> You have to remember to clone with `--recursive`, you have to remember how to update, new users have to learn what to do when "git diff" says "dirty", and `git clean -dfx` does not clean submodules, etc. If possible, I try to avoid them.

Thank you for your explanations @certik . Then it sounds better to commit it into the repo directly.
