### ISSUE TITLE
Missing "fypp" reference

### ISSUE THREAD

**Issue by MatthAlex** [fortran-lang/stdlib#154]
Building and compiling the project should retain the mention of what the preprocessor is, when should be installed (as a dependency) and where someone can find it.

At this state of the README and Wiki page, the build is failing (with just `cmake -B build`) as `fypp` might not be pre-installed.

**Comment by certik** [comment]
@MatthAlex thanks! I agree, we need to fix this. If you have a minute, you can submit a PR against README fixing it.

**Comment by MatthAlex** [comment]
I can certainly try!

**Comment by MatthAlex** [comment]
Thanks @JHenneberg!
Closing..
