### ISSUE TITLE
loadtxt and savetxt

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#16]
Implementation: https://github.com/certik/fortran-utils/blob/b43bd24cd421509a5bc6d3b9c3eeae8ce856ed88/src/utils.f90#L176

The interface is compatible with NumPy (e.g., you can do `savetxt` from Fortran and do `loadtxt` from NumPy and it just works, and vice versa). 

The `loadtxt` has the argument as `allocatable, intent(out)`, because you typically do not know the size of the matrix ahead of time.

NumPy: [savetxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html), [loadtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html)

**Comment by milancurcic** [comment]
I think these are great functions to start with and figure out the workflow. Good to go ahead as far as I'm concerened.

What module would this belong to? `stdlib_io` in `io.f90`?

**Comment by certik** [comment]
I think we agreed to prefix modules with `stdlib_`. 

The `io` module (`stdlib_io.f90`) might be a good name for it. NumPy has this directly in the `numpy` namespace, but I think we should have things in modules, not the global `stdlib` namespace. Because we can always later expose some frequently used functionality in `stdlib.f90` directly, but if we put it there now, it will be hard to remove later, as it would break people's code.

There is also `scipy.io`, with [loadmat](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html#scipy.io.loadmat) that loads Matlab's file.

So `stdlib_io.f90` works.

**Comment by jvdp1** [comment]
@certik Nice examples. I think it could be easily combine with something like

```
real, allocatable :: a(:)
type(File) :: f
f = File('log.txt')
call f%read(a)
call f%close()
```
Float, double-precision,integer,... could be then supported.

**Comment by milancurcic** [comment]
@certik Correct, I just re-read #9. `module stdlib_io` in `stdlib_io.f90` is good.

**Comment by milancurcic** [comment]
@jvdp1 Indeed, plain `savetxt` and `loadtxt` will be useful on their own, and the `File` derived type (a higher level abstraction) can later figure out if and how to use these more basic building blocks.

**Comment by certik** [comment]
I sent a PR in #23.

**Comment by jacobwilliams** [comment]
We can also get some inspiration from this csv read/write one of mine: https://github.com/jacobwilliams/fortran-csv-module

**Comment by certik** [comment]
@jacobwilliams good point, I created a standalone issue #24 for CSV. You are right that it is related, as in NumPy one can use [genfromtxt](https://stackoverflow.com/questions/3518778/how-do-i-read-csv-data-into-a-record-array-in-numpy#3519314) to read CSV.

**Comment by epagone** [comment]
Very nice start. What do you think of adding some optional functionalities like the following?

- Header handling (we might need to define a "comment" character that introduces the header):
  + when reading simply detect it and store it somewhere;
  + when writing add it and number the columns automatically (very useful for writing plotting scripts).
- column sorting or indexing using, for example, [ODERPACK](http://www.fortran-2000.com/rank/) (if there is no licence clash).

I found very useful (actually necessary) both them but I don't know how much general interest there is.

**Comment by certik** [comment]
@epagone, yes, we can add the `header`, `footer`, `comments`, `newline`, `delimiter` arguments for `savetxt` that NumPy has. We can also do the `fmt` argument and pass in Fortran formatting string.

All these arguments go after the `fname` and `X` arguments, so I think we can add them in subsequent PRs after #23 is merged.

Can you elaborate on the `column sorting or indexing using`? I don't think NumPy does that. What prevents the user to sort the data before calling `savetxt`?
