### ISSUE TITLE
Add syntax highlighting to fypp source files

### ISSUE THREAD

**Issue by ashwinvis** [fortran-lang/stdlib#185]
Since fypp is not officially supported:

- https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

It could be worthwhile to override syntax hightlighting in github. It would make it easier to browse the source code online. See:

- https://github.com/github/linguist#overrides
- github/linguist#1792

To do this one could add a `.gitattributes` file:
```
 *.fypp linguist-language=fortran 
```

Thoughts?

**Comment by jvdp1** [comment]
Thank you. It sounds good to me if it can help the users.

**Comment by ashwinvis** [comment]
Unfortunately it does not seem to work... :confused:

**Comment by ashwinvis** [comment]
I do not understand how this works. I get some highlighting (somewhat garbled, but better than nothing) in a fresh repo:

- https://github.com/ashwinvis/test-fypp-syntax/blob/master/checks.fypp

But not if I add it to a fork of stdlib

- https://github.com/ashwinvis/stdlib/blob/patch-1/src/stdlib_experimental_io.fypp

Perhaps GitHub does not render forks
