### ISSUE TITLE
Sparse matrix/vectors library

### ISSUE THREAD

**Issue by ghwilliams** [fortran-lang/stdlib#187]
I believe that a library of sparse matrix/vectors operations would be of great utility in stdlib.
So I would like to propose the creation of such a library (It looks like there is not such a library yet in stdlib). Of course I'm making myself avaiable in designing and coding.

regards
Williams

**Comment by certik** [comment]
@ghwilliams that's a great idea. Is what you propose different to #38? If not, then we can close this issue and continue the discussion at #38.

**Comment by ghwilliams** [comment]
Looks like the same. I will jump to #38 and see what is the current state of development of it.
I think you can close this issue @certik .
Thanks

**Comment by certik** [comment]
Cool thanks.
