### ISSUE TITLE
stdlib-docs action deletes CNAME

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#195]
You may have noticed that stdlib-docs are not served at stdlib.fortran-lang.org anymore, and are back at https://fortran-lang.github.io/stdlib-docs. 

This is because the GH Action that builds and deploys the docs [deletes the CNAME](https://github.com/fortran-lang/stdlib-docs/commit/b5d84b2cfc314ec17d8b8112277ad3722ec9b3a8).

@zbeekman how do we fix this?

**Comment by certik** [comment]
We just have to add the CNAME back in.

**Comment by milancurcic** [comment]
Okay, I will test it now.

**Comment by zbeekman** [comment]
There is a mechanism to add the CNAME when building... I'll PR

**Comment by zbeekman** [comment]
FYI: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-cname
