### ISSUE TITLE
Template Project depending on stdlib

### ISSUE THREAD

**Issue by MuellerSeb** [fortran-lang/stdlib#215]
My question from FortranCon:

It would be nice to provide a template for a Fortran package/project that depends on the stdlib, so that it is low-threshold for new users to adopt to your implementations. This could also automatically integrate `fpm`.
What do you think? Or is there already such a template?

**Comment by certik** [comment]
@MuellerSeb thanks for the idea. I think we'll provide an example with fpm. We first have to get fpm working with stdlib. Then to use it would be just adding `stdlib` to your dependencies.

**Comment by awvwgk** [comment]
I just tried to use stdlib as subproject in CMake and it is in fact currently impossible. I collected a patch for this in #284.

**Comment by awvwgk** [comment]
I created a template project using stdlib in CMake at https://github.com/awvwgk/stdlib-cmake-example, if there is interest I can transfer it to the @fortran-lang organization.

**Comment by milancurcic** [comment]
:+1: for fortran-lang/stdlib-cmake-example.

**Comment by awvwgk** [comment]
Looks like I cannot transfer the repo because I'm missing permissions in fortran-lang.

**Comment by milancurcic** [comment]
Okay, that will be easy to fix, but let's wait to hear from @certik @jvdp1 @ivan-pi @everythingfunctional and any others.

**Comment by jvdp1** [comment]
Thank you @awvwgk fr this proposition.
I think it is a good idea to move this in fortran-lang. When `fpm` will be ready to use `stdlib`, it will give a complete view on how to integrate easily stdlib with different tools. Some comments in the README of stdlib should be then probably added to point the users to this example.

**Comment by milancurcic** [comment]
Without no objections, stdlib-cmake-example has moved to [fortran-lang/stdlib-cmake-example](https://github.com/fortran-lang/stdlib-cmake-example). 

Thanks to @awvwgk for making it.
