### ISSUE TITLE
PR run failed: Build and Deploy Documents

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#237]
This morning I submitted a PR that failed, because I failed to properly update a CMakeLists.txt file and because my main testing processor, gfortran 10.2 on MacOS, was too forgiving in accepting F2018 semantics, and in initializing uninitialized attributes to zero. After testing with ifort 18.03 I was able to fix the obvious problems with my code, but then I got an email message with the header

[fortran-lang/stdlib] PR run failed: Build and Deploy Documents - Bitsets (3f6f77b)

and the body

Run failed for bitsets (3f6f77b)

Repository: fortran-lang/stdlib
Workflow: Build and Deploy Documents
Duration: 7.0 seconds
Finished: 2020-09-28 21:42:02 UTC

View results

Jobs:
Build-API-Docs failed (1 annotation)
—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here.

When I view results I get the link

https://github.com/fortran-lang/stdlib/actions/runs/277439934

Which tells me that the error occurred during the Build-API-Docs and it is an internal error. I suspect that it is either a problem with my markdown document, `doc/specs/stdlib_bitsets.md`, or with FORD attempting to process `src/stdlib_bitsets.f90`, `src/stdlib_bitset_64.f90`,or `src/stdlib_bitset_large.f90`. In either case I don't know how to fix the problem.  Any suggestions? Is it possible to kill a PR, and if so how?

**Comment by certik** [comment]
You can close any PR by simply clicking on the "Close" button. You can reopen a new PR with a new branch, or even the same branch.

**Comment by jvdp1** [comment]
As mentioned in [this comment](https://github.com/fortran-lang/stdlib/pull/236#issuecomment-700908433), I copied your branch in my repo, and all actions passed.
IMO, the best thing to do is to close #236 and open a new and clean PR, as explained in this [comment](https://github.com/fortran-lang/stdlib/pull/236#issuecomment-700908433)

**Comment by wclodius2** [comment]
I am now getting a similar sounding error, but the detailed error reported by "View workflow run" is different

1
Run sed -i .bak 's/^[[:blank:]]*graph:  *[Tt]rue/graph: false/' "${FORD_FILE}"
19
Error: Unable to process command '::set-env name=MAYBE_SKIP_SEARCH::--no-search' successfully.
20
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

It appears that GitHub has deprecated a `sed` command (`set-env`) that `FORD` processing currently uses.
