### ISSUE TITLE
Support for Intel oneAPI compilers

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#249]
I just tried to setup a CI for the Intel oneAPI compilers for stdlib and noticed that `src/tests/io/test_savetxt.f90` is triggering an ICE in `ifort` (see https://github.com/awvwgk/fortran-stdlib/runs/1439256395) and `src/stdlib_ascii.f90` is triggering an ICE in the `ifx` compiler (see https://github.com/awvwgk/fortran-stdlib/runs/1439276984).

I have seen there are compile issues with PGI/NVHPC, NAG and flang already for stdlib. Does this mean stdlib currently only supports GCC?

**Comment by ivan-pi** [comment]
The `ifx` error is not very informative:
```
/home/runner/work/fortran-stdlib/fortran-stdlib/src/stdlib_ascii.f90(73): catastrophic error: **Internal compiler error: internal abort** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
```

**Comment by ivan-pi** [comment]
The NAG issues were partially related to CMake - https://github.com/fortran-lang/stdlib/issues/108 - however, I am not sure if it was resolved. Presumably, PGI will also have issues with submodules, error stop, and other F2018 features.

The short answer to your question is yes.

**Comment by awvwgk** [comment]
I've never seen an informative ICE so far. Unfortunately, I don't have a local Intel oneAPI installation on my machine (yet), so I wasn't able to pin it down to a more specific part in the implementation. At least with Intel Parallel Studio stdlib builds just fine, so this seems to be Intel oneAPI specific.

**Comment by jvdp1** [comment]
> Does this mean stdlib currently only supports GCC?

I always try to compile `stdlib` with `gfortran` (9.3.1) and Intel `ifort` (19.1.1), and until now, it was always fine. I got some issues with one of the first versions of `ifort` 2017, but it has been solved with an update of `ifort`.
@awvwgk  Which version of `ifort` did you use?

I didn't test Intel oneAPI yet.

**Comment by awvwgk** [comment]
On my local machine, I use Intel Parallel Studio 2020, Update 2, which seems to work just fine.

On the CI example it should be Intel oneAPI 2021.1 beta10.

**Comment by milancurcic** [comment]
On my laptop (Ubuntu 20.04) I have ifort (IFORT) 2021.1 Beta 20200827 (from oneAPI) and it doesn't ICE until compiling the tests:

```
/home/milan/Work/fortran/stdlib/src/tests/io/test_savetxt.f90: catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
```

**Comment by milancurcic** [comment]
nvfortran 20.9-0 doesn't implement `real128` yet:

```
$ FC=nvfortran cmake .. -DCMAKE_MAXIMUM_RANK=4
-- The Fortran compiler identification is PGI 20.9.0
-- Check for working Fortran compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/nvfortran
-- Check for working Fortran compiler: /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/nvfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/nvfortran supports Fortran 90
-- Checking whether /opt/nvidia/hpc_sdk/Linux_x86_64/2020/compilers/bin/nvfortran supports Fortran 90 -- yes
-- Performing Test f18errorstop
-- Performing Test f18errorstop - Success
-- Performing Test f03rank
-- Performing Test f03rank - Failed
-- Performing Test f03real128
-- Performing Test f03real128 - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /home/milan/Work/fortran/stdlib/build
```

**Comment by jvdp1** [comment]
> I just tried to setup a CI for the Intel oneAPI compilers for stdlib and noticed that `src/tests/io/test_savetxt.f90` is triggering an ICE in `ifort` (see https://github.com/awvwgk/fortran-stdlib/runs/1439256395) and `src/stdlib_ascii.f90` is triggering an ICE in the `ifx` compiler (see https://github.com/awvwgk/fortran-stdlib/runs/1439276984).
> 
> I have seen there are compile issues with PGI/NVHPC, NAG and flang already for stdlib. Does this mean stdlib currently only supports GCC?

@awvwgk Did you report the ICEs to Intel? I just installed it on my local computer, and got also ICEs.

**Comment by Romendakil** [comment]
Hm, where did you get the Beta version for Intel 2021? Normally, I get informed when there is a new version. That they are having problems with their new release is deeply disturbing. Can someone give me a link to a product page?

**Comment by milancurcic** [comment]
@Romendakil FWIW I got it from [here](https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit.html). I followed the install instructions for apt on Ubuntu and installed basekit and hpckit. Beta 2021.1 is what's inside.

**Comment by awvwgk** [comment]
> Did you report the ICEs to Intel? I just installed it on my local computer, and got also ICEs.

Not yet, I finally got around to download the oneAPI compilers, but I still have to isolate the problem and create a minimal working example for a report.

**Comment by jvdp1** [comment]
> Update: The ICE in `ifort` will be fixed in the release version of oneAPI, I will open a PR to add the CI once oneAPI is finally out of beta.

Great. Thanks @awvwgk for the update.

**Comment by awvwgk** [comment]
Looks like there has been another update of the oneAPI compilers, but I'm very happy I did not get any of those, as they are completely broken now: https://github.com/awvwgk/fortran-stdlib/runs/1503801636#step:8:109

```
-- Check for working Fortran compiler: /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort  -- broken
CMake Error at /usr/local/share/cmake-3.16/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/runner/work/fortran-stdlib/fortran-stdlib/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_946e7/fast && /usr/bin/make -f CMakeFiles/cmTC_946e7.dir/build.make CMakeFiles/cmTC_946e7.dir/build
    make[1]: Entering directory '/home/runner/work/fortran-stdlib/fortran-stdlib/build/CMakeFiles/CMakeTmp'
    Building Fortran object CMakeFiles/cmTC_946e7.dir/testFortranCompiler.f.o
    /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort    -c /home/runner/work/fortran-stdlib/fortran-stdlib/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_946e7.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_946e7
    /usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_946e7.dir/link.txt --verbose=1
    /opt/intel/oneapi/compiler/2021.1.1/linux/bin/intel64/ifort      CMakeFiles/cmTC_946e7.dir/testFortranCompiler.f.o  -o cmTC_946e7 
    ifort: error #10105: ld: core dumped
    ifort: warning #10102: unknown signal(1776847024)
    ifort: error #10106: Fatal error in ld, terminated by unknown
    CMakeFiles/cmTC_946e7.dir/build.make:86: recipe for target 'cmTC_946e7' failed
    make[1]: *** [cmTC_946e7] Error 1
    make[1]: Leaving directory '/home/runner/work/fortran-stdlib/fortran-stdlib/build/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_946e7/fast' failed
    make: *** [cmTC_946e7/fast] Error 2
```
