### ISSUE TITLE
Implement sleep

### ISSUE THREAD

**Issue by certik** [fortran-lang/stdlib#266]
https://gcc.gnu.org/onlinedocs/gfortran/SLEEP.html

I had a real need here:

https://github.com/fortran-lang/stdlib/pull/265/commits/540e2f73ad841b7839f061db9980d982b4f7b943

For debugging purposes.

**Comment by jvdp1** [comment]
There is already a `sleep` in `stdlib` [here](https://github.com/fortran-lang/stdlib/blob/7b246420d8a3fdad70f65f6de25f2f218ad33df5/src/stdlib_system.F90#L5) .

Is it not what you want?

**Comment by urbanjost** [comment]
It looked like an implementation that was doing a sleep with a loop, if there is a sleep() already in stdlib that is great.

**Comment by jvdp1** [comment]
I will close this issue. @certik Please reopen it if you feel it is needed.

**Comment by certik** [comment]
Awesome, I missed it! I am sorry. I am glad it is already there.
