### ISSUE TITLE
stats: test mean fails for Windows MinGW32

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#274]
Just found this issue while trying the MSYS2 toolchains for different projects on GH actions. The test is passing in the MSYS POSIX environment and with the MinGW64 toolchain, but fails with the MinGW32 toolchain.

Output from the failing test is not very helpful:

```
17/24 Testing: mean
17/24 Test: mean
Command: "D:/a/fortran-stdlib/fortran-stdlib/build/src/tests/stats/test_mean.exe" "D:/a/fortran-stdlib/fortran-stdlib/build/src/tests/stats"
Directory: D:/a/fortran-stdlib/fortran-stdlib/src/tests/stats
"mean" start time: Dec 21 13:57 Coordinated Universal Time
Output:
----------------------------------------------------------
 Check failed.
ERROR STOP 1

Error termination. Backtrace:

Could not print backtrace: libbacktrace could not find executable to open
#0  0x714c6af3
#1  0x714590ce
#2  0x713aadb6
#3  0x4e9502
#4  0x43d07d
#5  0x41c45a
#6  0x43ce9d
#7  0x401395
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"mean" end time: Dec 21 13:57 Coordinated Universal Time
"mean" time elapsed: 00:00:00
----------------------------------------------------------
```

For details on the build see: https://github.com/awvwgk/fortran-stdlib/runs/1589260298?check_suite_focus=true

**Comment by jvdp1** [comment]
Thanks for reporting the issue. THe backtrace is not really useful :( Is there a way to get the output of the different tests to try to identify the problem?

**Comment by awvwgk** [comment]
The ctest log is uploaded here: https://github.com/awvwgk/fortran-stdlib/actions/runs/435893875#artifacts, I just copied the relevant part in the issue.

**Comment by awvwgk** [comment]
I could debug the failing tests a bit, the numerical thresholds are a bit too tight for Win32 in those two testcases:

https://github.com/fortran-lang/stdlib/blob/b0ab3bb0a09e4bf3c971bc4b8599d445fe4994f3/src/tests/stats/test_mean.f90#L109
https://github.com/fortran-lang/stdlib/blob/b0ab3bb0a09e4bf3c971bc4b8599d445fe4994f3/src/tests/stats/test_mean.f90#L123

**Comment by jvdp1** [comment]
Thank you. Annoying... Is increasing the threshold a possibility?

**Comment by awvwgk** [comment]
The deviation for the first case was `2.7061524833201538E-013`, slightly above the test threshold of `2.2204460492503131E-013`. I didn't investigate the second test case, but using `2000*epsilon(1._dp)` worked just fine.
