### ISSUE TITLE
CI fails in manual Makefile build

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#302]
Manual Makefile build fails following the merge of #301: https://github.com/fortran-lang/stdlib/runs/1724103766?check_suite_focus=true. I re-ran the jobs to make sure it's reproducible. It is. #301 build was fine at the PR stage. But I think it's incompatible with the parallel Makefile build introduced in #294.

**Comment by jvdp1** [comment]
Dependencies for some submodules seem to be missing. I'll have a look.
