### ISSUE TITLE
Provide a do nothing function.

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#316]
This is a proposal to implement a function that does nothing with its input arguments. I used a function like the one below to do nothing but acknowledge a compiler warning on an used dummy argument, which wasn't needed in the given context but couldn't be removed from the function signature. What do you think is there a need for such function in stdlib?

```f90
!> Do nothing but mark an unused dummy argument as such to acknowledge compile
!> time warning like:
!>
!>   Warning: Unused dummy argument ‘dummy’ at (1) [-Wunused-dummy-argument]
!>
!> We deeply trust in the compiler to inline and optimize this piece of code away.
elemental subroutine unused_dummy_argument(dummy)
  class(*), intent(in) :: dummy
  associate(dummy => dummy); end associate
end subroutine unused_dummy_argument
```

**Comment by ivan-pi** [comment]
How can we be sure, some compiler doesn't expand their definition of unused dummy arguments to include association without further usage? This would potentially further obfuscate the true source of an unused argument.

While I find those errors annoying in the case when dummy variables are required to match an abstract interface, I am skeptical whether this is really a better solution than simply acknowledging the unused variable in the documentation. 

In a subroutine with unused dummy variables, the caller still needs to provide them. An error message will at-least indicate to the developer those variables are unused. If the errors are silenced, the developer might wrongly believe their value must be set or has potentially changed.
