### ISSUE TITLE
Enable discussions for stdlib?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#330]
Should we enable discussions for the stdlib repository to have a separate space to talk more generally about stdlib related topics which are not a well contained issue and are not general enough for a discourse thread?

We have discussions enabled for [fpm](https://github.com/fortran-lang/fpm/discussions) and [stdlib-cmake-example](https://github.com/fortran-lang/stdlib-cmake-example/discussions).

Follow up from: https://fortran-lang.discourse.group/t/categories-for-the-fortran-lang-org-projects/775

**Comment by milancurcic** [comment]
I don't see why not. I just enabled it. If there are problems we can reconsider.
