### ISSUE TITLE
Unable to test the build of stdlib library using CMake

### ISSUE THREAD

**Issue by Aman-Godara** [fortran-lang/stdlib#348]
I was working in the directory `D:/GSoC/Fortran Codes` and used the command `cmake -B build -G Ninja` to get this message.

```-- The Fortran compiler identification is GNU 9.2.0
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: C:/MinGW/bin/gfortran.exe - skipped
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90
-- Checking whether C:/MinGW/bin/gfortran.exe supports Fortran 90 - yes
-- Performing Test f18errorstop
-- Performing Test f18errorstop - Success
-- Performing Test f03rank
-- Performing Test f03rank - Success
-- Performing Test f03real128
-- Performing Test f03real128 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: D:/GSoC/Fortran Codes/build
```

Then I ran the command `cmake --build build --target test` and got a very long error.
This is how the end of the error looks like:
```
Errors while running CTest
FAILED: CMakeFiles/test.util
cmd.exe /C "cd /D "D:\GSoC\Fortran Codes\build" && C:\Users\<myusername>\AppData\Roaming\Python\Python37\site-packages\cmake\data\bin\ctest.exe --force-new-ctest-process "
ninja: build stopped: subcommand failed.
```

I was working on a different version of the stdlib (after successfully pulling #346 to my local machine using `Git`) while I was following the instructions given in `README.md` file of stdlib. I was following the instructions from top to bottom one by one until I got this error.

I am using gfortran compiler `GNU Fortran (MinGW.org GCC Build-2) 9.2.0` and platform architecture is
![image](https://user-images.githubusercontent.com/34789087/111643006-98e0c680-8824-11eb-8734-12c7457cf9f3.png)
with `Windows 10` as the operating system. 
CMake version `cmake version 3.18.4`
Ninja version `1.10.0.git.kitware.jobserver-1`
fypp version `3.0`, python version `Python 3.7.7`

Can anyone please help me with it? Thank you.

**Comment by Aman-Godara** [comment]
Hey! Can anyone help me with this? I tried using gfortran `GNU Fortran (Rev9, Built by MSYS2 project) 10.2.0` but the problem persisted. The `README.md` file of `stdlib` says that people were able to successfully build `stdlib` with `MSYS version 10 of gfortran` but for me it failed. I will be grateful if anyone can help me with it. Thank you.

**Comment by LKedward** [comment]
Hi @Aman-Godara, did you run `cmake --build build` first, before running `cmake --build build --target test`?

**Comment by Aman-Godara** [comment]
> Hi @Aman-Godara, did you run `cmake --build build` first, before running `cmake --build build --target test`?

Yes. I did.

**Comment by LKedward** [comment]
You are perhaps missing a step, there are three separate commands to run:

`cmake -B build -G Ninja`

`cmake --build build`

`cmake --build build --target test`

**Comment by LKedward** [comment]
> I ran the command asked by you on a freshly cloned `stdlib` repository but I got errors. Can you please once check if current repository is successfully building on your local machine?

Yes I just ran these on the latest `stdlib` version. What errors are you getting now?

**Comment by Aman-Godara** [comment]
> > I ran the command asked by you on a freshly cloned `stdlib` repository but I got errors. Can you please once check if current repository is successfully building on your local machine?
> 
> Yes I just ran these on the latest `stdlib` version. What errors are you getting now?

It worked somehow this time. Thank you!!
