### ISSUE TITLE
Probably Index file of specs in documentation have wrong references for links

### ISSUE THREAD

**Issue by ChetanKarwa** [fortran-lang/stdlib#370]
The links given to the various specs in the index file of specs in the docs folder are revering to error 404.
Is this done on purpose which everyone plan to correct in future. Or is it wrong referencing? 
Probably all should be referenced to '.md' files instead of '.html'. Correct me if I am wrong.

**Comment by awvwgk** [comment]
Are you seeing 404 errors here https://stdlib.fortran-lang.org/page/specs/index.html or at the markdown source in this repository?

**Comment by ChetanKarwa** [comment]
Markdown in this repository.
I think that is not the correct way to refer to the files.
My bad!!

**Comment by ChetanKarwa** [comment]
Maybe we can put the complete links to the page so we won't get 404 in the markdown source files too.
