### ISSUE TITLE
Problems using Makefile.manual on OS X V11.2.3 "BigSur"

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#371]
I am testing out some possible additions to stdlib. During initial development CMake has worked well in compiling the source code. I would now like to appropriately modify Makefile.manual so that it can also be used to compile the files. I am getting a load time error for gfortran 10.2.0: "ld: library not found for -lSystem". Is there some obvious change I can do so that Makefile.manual will work? I assume I need to modify the library search path.

**Comment by ivan-pi** [comment]
Closing due to #657 (Remove support for manual make builds).
