### ISSUE TITLE
Build failures on Mac OS X

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#389]
I am attempting to fix issue #383. My attempt to do a pull request has run into two failure both on a Mac OS X. Both related to the downloading and installation of software to process the pulls, and not due to the material in the pull request.

For Build API Docs after installing GFortran Mac OS
...
Successfully installed fypp-3.0 lxml-4.6.3
==> Downloading https://homebrew.bintray.com/bottles/jasper-2.0.28.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "jasper"
Download failed: https://homebrew.bintray.com/bottles/jasper-2.0.28.catalina.bottle.tar.gz
Error: Process completed with exit code 1.

For CI workflow run Build (macOS-latest, 7)
...
Run brew install gcc@${GCC_V} || brew upgrade gcc@${GCC_V} || true
==> Downloading https://homebrew.bintray.com/bottles/gcc%407-7.5.0_3.catalina.bottle.tar.gz
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "gcc@7"
Download failed: https://homebrew.bintray.com/bottles/gcc%407-7.5.0_3.catalina.bottle.tar.gz
Error: gcc@7 not installed
Error: No such keg: /usr/local/Cellar/gcc@7
Error: Process completed with exit code 1.
...
Run cmake --build build --verbose --parallel 1
Error: /Users/runner/work/stdlib/stdlib/build is not a directory
Error: Process completed with exit code 1.

**Comment by awvwgk** [comment]
I think this has resolved itself
