### ISSUE TITLE
Compilation problems using CMake and ifort (IFORT) 18.0.3 20180410

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#390]
My version of ifort
ifort (IFORT) 18.0.3 20180410
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
is having trouble compiling `stdlib` when invoked using make. In particular while compiling stdlib_quadrature_simps.f90 I am getting multiple messages of the form
```
    ...stdlib_quadrature_simps.f90(50): error #6284: There is no matching specific function for this generic function reference.   [SIMPS]
                        integral =  simps38(y(1:4), dx) + simps(y(4:6), dx)
    ------------------------------------------------------^
```

FWIW I get no messages when compiling with gfortran 10.2.

**Comment by awvwgk** [comment]
Duplicate of https://github.com/fortran-lang/stdlib/issues/299

**Comment by awvwgk** [comment]
stdlib currently requires Intel Fortran 19 or newer, not sure how difficult it would be to make it compatible for the previous versions.

**Comment by awvwgk** [comment]
Just checked Intel version 18.0.5.20180823, which doesn't throw the above error.

**Comment by wclodius2** [comment]
Thanks

**Comment by 14NGiestas** [comment]
Closing in favor of #299
