### ISSUE TITLE
Building with GCC 11 fails

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/stdlib#416]
GCC 11 is now available and we already have packages for [Ubuntu 21.04](https://packages.ubuntu.com/hirsute/gfortran-11) and [homebrew](https://formulae.brew.sh/formula/gcc), would be nice if we could start testing this here as well. Since our Linux runner is using Ubuntu 20.04 it might be a bit more involved to install GCC 11 there.

**Comment by jvdp1** [comment]
AFAIK Ubuntu 21.04 is not available among the supported Github runners.

[Here](https://github.com/actions/virtual-environments/issues/3280) and [here](https://github.com/actions/virtual-environments/pull/32910) are some discussions on GCC 11 on Ubuntu 20.04

**Comment by awvwgk** [comment]
We are triggering an ICE with GCC 11 in `stdlib_optval`:

```
cd /home/runner/work/stdlib/stdlib/build/src/tests/optval && /usr/bin/gfortran-11  -I/home/runner/work/stdlib/stdlib/build/src/mod_files  -O3 -DNDEBUG -O3   -fimplicit-none -ffree-line-length-132 -Wall -Wextra -Wimplicit-procedure -Wconversion-extra -pedantic-errors -std=f2018 -Wno-error=pedantic -c /home/runner/work/stdlib/stdlib/src/tests/optval/test_optval.f90 -o CMakeFiles/test_optval.dir/test_optval.f90.o
f951: internal compiler error: Segmentation fault
0xd40aeb internal_error(char const*, ...)
	???:0
0x15913ef gfc_resolve_code(gfc_code*, gfc_namespace*)
	???:0
0x1572ad1 gfc_parse_file()
	???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.
```

**Comment by LKedward** [comment]
I opened a possible fix in https://github.com/awvwgk/fortran-stdlib/pull/80. Works locally, but not tested in Github actions CI yet.

**Comment by awvwgk** [comment]
This seems to do the trick, thanks.

**Comment by brocolis** [comment]
For information, current git~master builds unmodified with GCC-11-x86-64 on Windows 10 x64, using `make -f Makefile.manual FYPPFLAGS=-DMAXRANK=4 clean test`.

**Comment by awvwgk** [comment]
Maybe worth reporting on https://gcc.gnu.org/bugzilla/, `stdlib_optval.fypp` should be self-contained enough for a good minimal reproducer. I might be able to upgrade my toolchains to GCC11 by the end of this month and create a report, until then please feel free to go ahead, report this issue and post the ticket here if you have already a GCC11 version around.
