### ISSUE TITLE
Sorting tests are too large

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#434]
They take about 80 s on my laptop. Before this test, the entire suite ran in under a second.

Can the sorting tests be reduced such that they run fast--ideally under a second? I see some parameters that seem relevant:

```
    integer(int32), parameter :: test_size = 2_int32**20
    integer(int32), parameter :: char_size = 26**4
    integer(int32), parameter :: string_size = 26**3
    integer(int32), parameter :: block_size = test_size/6
    integer, parameter        :: repeat = 8
```

Can these parameters be tuned down so that the tests are short yet remain meaningful? @wclodius2 @jvdp1

**Comment by wclodius2** [comment]
The numbers were chosen to:
1. Test the behavior of the sorting routines on large arrays.  For that I choose `2**20` elements for the integer arrays. Now that they have been tested we might choose smaller arrays.
2. For the comparisons in the sorting was much slower so I choose smaller arrays of `26**4` and `26**3`. Though significantly smaller number of element they individually take a comparable amount of time to the integer arrays. The `26**4` might be reduced to `26**3`.
3. To reduce the "noise" in the comparisons each sort is repeated eight times, and an average sorting time is reported. If we are not concerned about benchmarking repeat could be  set  to  one.

**Comment by awvwgk** [comment]
It might be worth to separate unit testing from benchmarking. CMake supports separate test suites, we can have a short testsuite which will can run regularly when developing and an additional benchmark testsuite which will always run on the CI here.

**Comment by wclodius2** [comment]
I have committed [changes](https://github.com/fortran-lang/stdlib/pull/439) to make `test_sorting.f90` run on a much shorter time scale. I would appreciate pull reviews by two reviewers  with write privileges.

**Comment by gareth-nx** [comment]
I believe this can be closed
