### ISSUE TITLE
MAXRANK error in stdlib with cmake 

### ISSUE THREAD

**Issue by Aman-Godara** [fortran-lang/stdlib#466]
**Describe the issue**

I did `git reset --hard origin/master` on my local master branch to get my local branch updated to the latest commit. But when I try to do `cmake --build build` on this, I get this error:

![image](https://user-images.githubusercontent.com/34789087/125937296-58ee11da-6455-49f0-846d-a8043b5cd173.png)

I have pasted only the recurring part of the error. This same error has appeared for 6 files including `stdlib_linalg.f90`.
I doubt that it is because of some local changes because other branches (which are not updated to the latest commit) which used to run successfully back then have suddenly started giving this error. I am unable to understand what has changed locally.

After to this, I did `cmake -B build -G Ninja` but to no success.

**Technical Details**

*stdlib version*: latest

*Compiler version*: GCC 10.2.0

*Platform and Architecture*: Windows 10

**Comment by jvdp1** [comment]
I have no problem on Linux.

Note that `MAXRANK` should be equal to a number (e.g. 4), and not ot `ON/OFF`.

**Comment by Aman-Godara** [comment]
I didn't change `MAXRANK` manually. How can I change it a number let's say 4?

**Comment by jvdp1** [comment]
> I didn't change `MAXRANK` manually. How can I change it a number let's say 4?

You can find some explanations [here](https://github.com/fortran-lang/stdlib#build-with-cmake), with e.g.

````
cmake -B build -G Ninja -DCMAKE_MAXIMUM_RANK:String=7 -DCMAKE_INSTALL_PREFIX=$HOME/.local
````

@awvwgk might help you further since you are on Windows.

**Comment by Aman-Godara** [comment]
Thanks it worked! @jvdp1.
