### ISSUE TITLE
CMake build in place or copy test files

### ISSUE THREAD

**Issue by pdebuyl** [fortran-lang/stdlib#47]
Without the datafiles, the test would fail on my machine when running an out of source build.

The branch here https://github.com/pdebuyl/stdlib/tree/cmake_copy_dat_files make a copy of the data files. I preferred to open an issue since I don't know if a PR would be of any use here.

**Comment by certik** [comment]
Can you please submit a PR to fix CMake to work out of tree?

That would be very helpful. Thanks!
