### ISSUE TITLE
Explain that setting -DMAXRANK=4 reduces compilation time

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/stdlib#492]
Here is a minor suggestion for the Readme.md. It says

You can limit the maximum rank by setting -DMAXRANK=<num> in the FYPPFLAGS environment variable:

`make -f Makefile.manual FYPPFLAGS=-DMAXRANK=4`

It may not be obvious to a new user why one would do this, but this drastically reduces the compilation time compared to 

`make -f Makefile.manual`

So I suggest adding a sentence after the first command above: "Doing this substantially reduces compilation time."

**Comment by gareth-nx** [comment]
Hi @Beliavsky. 

In case you'd consider using this issue to propose a simple pull request with a fix -- there is a tutorial on how to do that [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). 

My git skills are not yet sufficient to make proper contributions, but I followed that tutorial a few months ago to make a simple documentation fix, and found it relatively straightforward.

**Comment by milancurcic** [comment]
Fixed by #501.
