### ISSUE TITLE
Problems with FPM and updating a PR

### ISSUE THREAD

**Issue by wclodius2** [fortran-lang/stdlib#557]
I have submitted a PR for hash functions and pushed my initial code a couple of weeks ago with no problems. I then found some problems with a module and pushed the correction. This led to a message with the header "[wclodius2/stdlib] Run failed: fpm-deployment - hash_functions (7be16f3)". The error report is for 
Install fpm latest release

with the detailed message

Run fortran-lang/setup-fpm@v3
10
use-haskell: false
11
fpm-version: latest
12
fpm-repository: https://github.com/fortran-lang/fpm
13
This platform is linux
14
Fetching fpm from https://github.com/fortran-lang/fpm/releases/download/current/fpm-current-linux-x86_64
15
Error: Error while trying to fetch fpm - please check that a version exists at the above release url.
16
undefined
17
Error: The "path" argument must be of type string. Received type undefined

It looks like FPM has become required since the initial push. I can see three issues in the error report:
1. It is unable to find the specified version of fpm at the specified path.
2. The specified version is for Linux while I do development in MacOSX.
3. The path argument is not specified to be a string (although it seems to show a path in the report)

What can I do to fix it on my end? Is there something that needs to be fixed in the use of fpm by the repository?

**Comment by awvwgk** [comment]
Reported in https://github.com/fortran-lang/setup-fpm/issues/6

You can fix it for now by pinning to a specific version (`fpm-version: v0.4.0`), which I would recommend rather than relying on the latest.

**Comment by wclodius2** [comment]
Where do I look to find out how to pin to a specific version?

**Comment by awvwgk** [comment]
I opened #558 to pin fpm to version 0.4.0 in the testing.

**Comment by wclodius2** [comment]
Will that automatically start testing for my PR or is there something else I have to do?

**Comment by awvwgk** [comment]
You would have to cherry-pick the commit, merge back the default branch or rebase your branch once the patch is merged.
