### ISSUE TITLE
Preprocessor fypp not found! during cmake run.

### ISSUE THREAD

**Issue by iajzenszmi** [fortran-lang/stdlib#575]
### Description

ian@ian-Aspire-One-753:~/fortran-stdlib/stdlib$ cd ~/fortran-stdlib
ian@ian-Aspire-One-753:~/fortran-stdlib$ cmake stdlib
-- The Fortran compiler identification is GNU 9.3.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Performing Test WITH_QP
-- Performing Test WITH_QP - Success
-- Performing Test WITH_XDP
-- Performing Test WITH_XDP - Success
-- Performing Test f18errorstop
-- Performing Test f18errorstop - Success
-- Performing Test f03rank
-- Performing Test f03rank - Success
-- Performing Test f03real128
-- Performing Test f03real128 - Success
CMake Error at CMakeLists.txt:57 (message):
  Preprocessor fypp not found!

### Expected Behaviour

A clean run to produce the Makefile.

### Version of stdlib

Fork 88

### Platform and Architecture

Ubuntu Linux

**Comment by milancurcic** [comment]
Thanks, @iajzenszmi. Have you installed fypp? See [stdlib requirements](https://github.com/fortran-lang/stdlib#requirements).

**Comment by iajzenszmi** [comment]
ian@ian-Aspire-One-753:~/fortran-stdlib$ pip3 install fypp
Collecting fypp
  Downloading fypp-3.1.tar.gz (68 kB)
     |████████████████████████████████| 68 kB 1.7 MB/s 
Building wheels for collected packages: fypp
  Building wheel for fypp (setup.py) ... done
  Created wheel for fypp: filename=fypp-3.1-py3-none-any.whl size=28563 sha256=ccbdc2667a264c698ac8b0c4ff60a5834683655a4a357b8f5bbda1047b64db59
  Stored in directory: /home/ian/.cache/pip/wheels/76/c2/06/b710491cffafad23fa1f4e02f98471105137b3dc42c2f12293
Successfully built fypp
Installing collected packages: fypp
Successfully installed fypp-3.1
ian@ian-Aspire-One-753:~/fortran-stdlib$ cmake stdlib
-- test-drive: Find installed package
-- Retrieving test-drive from https://github.com/fortran-lang/test-drive
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ian/fortran-stdlib
Thanks. I have just installed fypp and the problem is solved.
