### ISSUE TITLE
stdlib version information function

### ISSUE THREAD

**Issue by brocolis** [fortran-lang/stdlib#576]
### Motivation

It would be good to have a function `stdlib_version()`

```
function stdlib_version() result(r)
    character(len=:), allocatable :: r
    r = "v0.1.0"
end function
```

This information is useful for external build tools, and for bug reporting.

**Comment by awvwgk** [comment]
Good idea, we should have this information available.

I added a patch to handle the version information automatically in CMake, make and fpm. As well as providing a preliminary getter function to retrieve the version data either as numeric values or as string in #579. Feedback is welcome.
