### ISSUE TITLE
Possible issue: "No tests were found!!!" in CI Build (ubuntu-latest, 9, cmake)

### ISSUE THREAD

**Issue by jvdp1** [fortran-lang/stdlib#587]
I just noticed that no tests are found fo the CI "Build (ubuntu-latest, *, cmake"). See, e.g. [this action](https://github.com/fortran-lang/stdlib/runs/4398555214?check_suite_focus=true).
Therefore, sometimes, the actions are ok, while they should failed it the tests were properly run.

Did I miss somet discussions? Is this on purpose?

**Comment by awvwgk** [comment]
See https://gitlab.kitware.com/cmake/cmake/-/issues/19670, which can be turned into an error with https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4258. CMake 3.16 doesn't allow to make this an error unfortunately, but newer versions allow passing `--no-tests=error` to CTest.
