### ISSUE TITLE
License

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#6]
How should Fortran stdlib be licensed?

I initially chose my favorite license, which is MIT. We can discuss and change this if other license is preferred. 

I think it's important that the license:

* is friendly for commercial / closed-source projects;
* grants copyright to contributors

What else or anything I'm missing?

**Comment by zbeekman** [comment]
I too like MIT, FWIW.

**Comment by scivision** [comment]
LLVM C++ stdlib is MIT https://libcxx.llvm.org/

**Comment by certik** [comment]
I think we should use MIT.

**Comment by milancurcic** [comment]
Closing this for now, it looks like we will mostly be on the same page. Please re-open if needs to be reconsidered.
