### ISSUE TITLE
Discussion of `diff` procedure

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/stdlib#606]
### Motivation

Here are some questions about the `diff` procedure:

- Is it worth introducing `diff` procedure?
- API of `diff` procecure?
  Function? Subroutine?
- Return value: `allocatbable` array or `automatic` array?

#605 is about the submission of `diff`, it seems that the efficiency of this implementation needs to be improved. Its API needs to be discussed and reached a consensus.

@gareth-nx has some suggestions in #605. (see [ here ](https://github.com/fortran-lang/stdlib/pull/605#discussion_r772196313) )
- Efficiency
- API
- User-oriented

### Prior Art

- [`diff` in Matlab](https://ww2.mathworks.cn/help/matlab/ref/diff.html?lang=en)
```matlab
Y = diff(X)
Y = diff(X,n)
Y = diff(X,n,dim)
```
- [`diff` in numpy](https://numpy.org/doc/stable/reference/generated/numpy.diff.html)
```python
Y = numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
```
Note: 
`prepend, append: array_like, optional`: New in numpy version 1.16.0.

**Comment by gareth-nx** [comment]
I note the optional arguments `prepend` and `append` in the numpy routine seem to give a flexible treatment of the end-points issue raised in #605. The matlab version doesn't offer that - it just reduces reduces the output size (or first dimension size) by 1.

**Comment by LKedward** [comment]
> * Is it worth introducing `diff` procedure?

Yes, I use this a lot in MATLAB.

> * API of `diff` procecure?

IMO, it makes sense to stick closely to the API of prior art with MATLAB and numpy because this is what people will be used to.
I didn't know numpy provided the `prepend` and `append` options, they look useful.

>   Function? Subroutine?

How has this question (function vs subroutine) been approached in the rest of `stdlib` for math operations?
(The argument has been made elsewhere that the additional overheads of array function calls is simply a question of compiler implementation, which could be solved in the compiler)

**Comment by gareth-nx** [comment]
> How has this question (function vs subroutine) been approached in the rest of stdlib for math operations?

One option would be to expose both function (`diff`) and subroutine (`difs`) interfaces? Internally the former could take care of allocation and then call the latter. `difs` could assume that the user-provided output array has the right shape.

**Comment by jvdp1** [comment]
Thank you for this proposition.

> * Is it worth introducing `diff` procedure?

Yes, I think so. E.g., it could be used in a function `mode` in the module `stdlib_stats`.

> * API of `diff` procecure?
I suggest to stay as close as possible to the ones implemented in other languages, like `matlab`, `octave` or `Julia`.

Supporting an `optional` mask might be an advantage.

>   Function? Subroutine?
> * Return value: `allocatbable` array or `automatic` array?

Usually such procedures are implemented as functions with automatic arrays in `stdlib`.

**Comment by zoziha** [comment]
Thank you very much for your all feedback~

If we decide to introduce the `prepend` and `append` arguments (array_like) in the `diff` function, it seems that we may need to consider introducing a similar `append` function to stitch the arrays (`prepend`, `diff` and `append` arrays) ?? :

- [numpy.append](https://numpy.org/doc/stable/reference/generated/numpy.append.html)
- matlab. [horzcat](https://ww2.mathworks.cn/help/matlab/ref/horzcat.html?lang=en) / [vertcat](https://ww2.mathworks.cn/help/matlab/ref/vertcat.html?lang=en) / [cat](https://ww2.mathworks.cn/help/matlab/ref/double.cat.html?lang=en)

**Comment by gareth-nx** [comment]
> Usually such procedures are implemented as functions with automatic arrays in stdlib.

If we are to support `prepend` and `append` as optional arguments then I don't think this will work, as the size of the output arrays will be `size(input) + size(prepend) + size(append)`. I assume we can't use that expression to declare the automatic output array size if `prepend` and `append` are optional (?).

> If we decide to introduce the prepend and append arguments (array_like) in the diff function, it seems that we may need to consider introducing a similar append function to stitch the arrays (prepend, diff and append arrays) ?? 

I assumed that, rather than perform array stitching, we could compute the differences associated with `prepend` and `append` in a separate part of the code within e.g. `if(present(append)) then ...` and similarly for `prepend`. The approach you suggest would be more elegant, but might be slower due to the array stitching.

Both issues above would be avoided if we don't support `append` and `prepend`. This is one argument for not supporting those options. 

OTOH, `diff` is simple enough for most users to implement themselves efficiently inline (`x(2:N) - x(1:N-1)`). Given that, IMO it is preferable for the `stdlib` implementation to be "possible to use efficiently" (even if not as efficient as user-inlined code in every case) and provide a few conveniences to users. On those grounds I like the idea of `append`, `prepend`, and a subroutine interface (or some other interface that can avoid the allocation).

**Comment by zoziha** [comment]
I tried to build on the previous `diff` commits and **made a poor implementation only for our discussion** (see [stdlib_math_diff.fypp](https://github.com/fortran-lang/stdlib/blob/8561c45325589b1e49a90b5e7b0e804a81786054/src/stdlib_math_diff.fypp)), adding support for the `prepend` and `append` arguments, but I believe this does increase the complexity of the internal implementation of `diff`.

https://github.com/fortran-lang/stdlib/blob/8561c45325589b1e49a90b5e7b0e804a81786054/src/stdlib_math_diff.fypp#L92~L99

I still hope to implement functions like `numpy.append` in stdlib to facilitate stitching arrays.
This will also improve the existing `diff` implementation, which is not only elegant, but also clean and easy to maintain.

**Comment by gareth-nx** [comment]
Thanks @zoziha for the discussion implementation.

I wonder if we should only support `rank 1` and `rank 2` arrays (as in the draft implementation)? 

Both matlab and numpy support arrays of any rank. OTOH, R only supports rank1 arrays.

Is there much value to the `rank > 1` case (as compared to users doing the required calculation in a loop)? Rather than supporting `rank=1,2` but not other ranks, it might be conceptually simpler to just support `rank=1`, and suggest looping for other ranks (??). Or support all ranks?

**Comment by gareth-nx** [comment]
FWIW I've been exploring some alternative implementations (very preliminary, only for `real, rank=1` arrays). 

The gist [here](https://gist.github.com/gareth-nx/30e3ffd0b5084d2e5e71c797b1a46bf4) contains:
*  a build script
*  a program run_test.f90 (that also uses the draft stdlib version of diff), and 
*  a module with an alternative function (`diff`) and subroutine (`difs`) implementations, where the latter is inflexible, and the former is like the `stdlib` rank=1 version. 

If you copy them all to the same directory, modify `build.sh` to include your stdlib environmental variables, then it can be compiled by running `source build.sh`.

I used `gfortran -O3` to compile it (which is the same that I am using for `stdlib`).

 I find the timings are often a bit faster (1.5-2) for the alternative versions, compared to the current stdlib draft, when the array size ranges from 100 to 10000.  With a very large array size the timings become more similar. 

```
(base) gareth@gareth-P410:~/Code_Experiments/fortran/stdlib/random_tests/diff$ source build.sh 
(base) gareth@gareth-P410:~/Code_Experiments/fortran/stdlib/random_tests/diff$ ./run_test 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   1.11642039    
 Time ratio (stdlib_function / local_function  ) :  0.765917778    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   1.89878118    
 Time ratio (stdlib_function / local_function  ) :   1.39779246    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   1.86874056    
 Time ratio (stdlib_function / local_function  ) :   1.63502300    
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   1.12102830    
 Time ratio (stdlib_function / local_function  ) :  0.763218284    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   1.95850849    
 Time ratio (stdlib_function / local_function  ) :   1.53631270    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   2.04555464    
 Time ratio (stdlib_function / local_function  ) :   1.57685053    

```

Very much an experiment, but maybe something is of use.

**Comment by zoziha** [comment]
The operating efficiency of subroutines is higher than that of functions. I think array functions are more suitable for **creating** a new array and data, and subroutines are more suitable for **overwriting and refreshing** array data.

From this perspective, creating a subroutine `difs` is efficient and demanding?

**Comment by gareth-nx** [comment]
I re-ran the timing test mentioned above, using the recently pushed version of the pull request. 

In the case where we use `append/prepend`: 
* For mid sized arrays (size of 100 - 10000) it still has a noticeable time penalty compared to the function version in the [gist](https://gist.github.com/gareth-nx/30e3ffd0b5084d2e5e71c797b1a46bf4), although is faster than the previous stdlib pull-request version.
* For large arrays (10-million entries) it is slightly faster than the function version in the [gist](https://gist.github.com/gareth-nx/30e3ffd0b5084d2e5e71c797b1a46bf4), and slightly slower than the inflexible subroutine version.

I wonder if this difference is related to the `work` array being allocatable in the stdlib version, vs automatic in the gist version? The gist version achieves that by having a worker subroutine with no optional arguments. It would be nice if we could make the stdlib version at least as efficient (or, understand why we can't). 

If we find there are persistent speed advantages to the subroutine interface, I would lean toward exposing a subroutine interface (even if it's less convenient) as well as a function interface.  


```
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   1.09848988    
 Time ratio (stdlib_function / local_function  ) :  0.752216458    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   2.02271032    
 Time ratio (stdlib_function / local_function  ) :   1.64654362    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           1
 Time ratio (stdlib_function / local_subroutine) :   1.98440468    
 Time ratio (stdlib_function / local_function  ) :   1.46916664    
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   1.07091498    
 Time ratio (stdlib_function / local_function  ) :  0.734303594    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   2.03846216    
 Time ratio (stdlib_function / local_function  ) :   1.62488389    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   2.11474347    
 Time ratio (stdlib_function / local_function  ) :   1.43239534    
```

**Comment by gareth-nx** [comment]
It's also interesting to compare the performance vs writing`(x(2:) - x(1:size(x)-1)` in-line , in the common case where `prepend, append` are not provided, and `n=1`. 

It turns out the inline version is about 6x faster (or in the best cases, 2.5-3x vs the subroutine). Here is the output where `inline_without_prepend_or_append` refers to the special case.
```
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   1.08094656    
 Time ratio (stdlib_function / local_function  ) :  0.750260413    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   6.21810484    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   1.96804166    
 Time ratio (stdlib_function / local_function  ) :   1.24381065    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   5.96953821    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   2.40701604    
 Time ratio (stdlib_function / local_function  ) :   1.19632530    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   6.17020941    
```

However much of the performance can be regained by giving special treatment of that case in the function and subroutine implementation. Using the versions in [this gist](https://gist.github.com/gareth-nx/b079ba38509464fdf2441ec1594b827d) I get:
```
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   6.24738979    
 Time ratio (stdlib_function / local_function  ) :   1.99576485    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   6.25094366    
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   6.19736195    
 Time ratio (stdlib_function / local_function  ) :   3.57656074    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   6.12597227    
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / local_subroutine) :   3.87429070    
 Time ratio (stdlib_function / local_function  ) :   3.07483053    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   5.73714638    
```

Summary:
* There seems to be an argument for implementing special-cases efficiently in the stdlib routines. 
*  I imagine this approach could be generalised to treat the case where `n=1` even when we do have `prepend, append` (since in that case, one could avoid the `work` allocation easily enough).

**Comment by jvdp1** [comment]
> I wonder if we should only support `rank 1` and `rank 2` arrays (as in the draft implementation)?
> 
> Both matlab and numpy support arrays of any rank. OTOH, R only supports rank1 arrays.
> 
> Is there much value to the `rank > 1` case (as compared to users doing the required calculation in a loop)? 

I don't know if there is interest for supporting more than rank-1 (and 2). Maybe @LKedward can give his experience on this?
Anyway such a support could be implemented with `fypp` (see e.g., all stats functions), if there is an interest.

**Comment by jvdp1** [comment]
@gareth-nx I didn't check all the details, but I guess that the difference may come from the fact that some arrays are on the stack, while others are on the heap (automatic vs allocatable arrays). This behaviour depends on the compiler. But adding an option to ensure that all arrays are on the heap/stack could remove some of the time difference.

**Comment by LKedward** [comment]
I've only ever used it with rank 1 and rank 2 arrays. Can't think of any uses for higher ranks, but there may be some. For an initial implementation, I think support for rank 1 and rank 2 is sufficient.

**Comment by gareth-nx** [comment]
Dear @zoziha 
Thanks for your work on this. Below is an edit to your current diff function with 2 changes:
* It uses `block` to make `work` an automatic array, rather than allocatable.
* It gives special treatment of the special case that `size_present == size_append == 0 .and. n==1`. 

My tests suggest they make the code much faster for the special case, and a bit faster for other cases. 

Could you please consider whether this will speed up the code, and otherwise be a good trade-off? 

```fortran
    #:for k1, t1 in RI_KINDS_TYPES
    pure module function diff_1_${k1}$(x, n, prepend, append) result(y)
        ${t1}$, intent(in) :: x(:)
        integer, intent(in), optional :: n
        ${t1}$, intent(in), optional :: prepend(:), append(:)
        ${t1}$, allocatable :: y(:)
        integer :: size_prepend, size_append, size_x
        !! Remove "work" -- use "block" and an automatic array below.
        !${t1}$, allocatable :: work(:)
        integer :: n_, i

        n_ = optval(n, 1)
        if (n_ <= 0) then
            y = x
            return
        end if

        size_prepend = 0
        size_append = 0
        if (present(prepend)) size_prepend = size(prepend)
        if (present(append)) size_append = size(append)
        size_x = size(x)

        if (size_x + size_prepend + size_append <= n_) then
            allocate(y(0))
            return
        end if

        if(size_prepend == 0 .and. size_append == 0 .and. n_ == 1) then
            ! Use a quick exit for the common case, to avoid memory allocation.
            y = x(2:) - x(1:(size_x - 1))
            return
        end if

        ! By using 'block' we can declare work as an automatic array. This seems faster.
        block
        ${t1}$ :: work(size_x + size_prepend + size_append)
        !allocate(work(size_x + size_prepend + size_append))
        if (size_prepend > 0) work(:size_prepend) = prepend
        work(size_prepend+1:size_prepend+size_x) = x
        if (size_append > 0) work(size_prepend+size_x+1:) = append

        do i = 1, n_
            work(1:size(work)-i) = work(2:size(work)-i+1) - work(1:size(work)-i)
        end do

        y = work(1:size(work) - n_)
        end block

        !call move_alloc(work, y)
        !y = y(1:size(y)-n_)

    end function diff_1_${k1}$
```

**Comment by zoziha** [comment]
Okay, I updated the content of `diff`. ([see here](https://github.com/fortran-lang/stdlib/pull/605/commits/bd52051a123c8a0bd685760861b001eb87477fd3))
And I used `gfortran/ifort` on my windows computer for some simple tests, and the time efficiency was indeed improved.
This is indeed an interesting `block` synatx usage, I haven't seen this before. 👍

**Comment by gareth-nx** [comment]
That's good to hear. I also had never used `block` like that until now -- and didn't realise it could improve optimization.

**Comment by gareth-nx** [comment]
FWIW I have re-run the [gist code](https://gist.github.com/gareth-nx/b079ba38509464fdf2441ec1594b827d) using the updated stdlib pull request. 

The speed of new version is certainly closer to the hand-written function (but mostly slightly slower -- I don't know why).

It is most often a factor of 2 to 3 slower than the inflexible subroutine version.
 
```
(base) gareth@gareth-P410:~/Code_Experiments/fortran/stdlib/random_tests/diff$ ./run_test 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           1
            495534454            458510801            655676794
 Time ratio (stdlib_function / local_subroutine) :   1.08074760    
 Time ratio (stdlib_function / local_function  ) :  0.755760252    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           1
            140064877             69584748            125461367
 Time ratio (stdlib_function / local_subroutine) :   2.01286745    
 Time ratio (stdlib_function / local_function  ) :   1.11639845    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           1
            221124485            104447588            167607181
 Time ratio (stdlib_function / local_subroutine) :   2.11708570    
 Time ratio (stdlib_function / local_function  ) :   1.31930196    
 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
            251872695             76037524            243478961
 Time ratio (stdlib_function / local_subroutine) :   3.31247902    
 Time ratio (stdlib_function / local_function  ) :   1.03447413    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   3.33093452    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
             64889342             20440179             37482766
 Time ratio (stdlib_function / local_subroutine) :   3.17459750    
 Time ratio (stdlib_function / local_function  ) :   1.73117805    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   3.15032911    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
            108372210             52738655             64814185
 Time ratio (stdlib_function / local_subroutine) :   2.05489135    
 Time ratio (stdlib_function / local_function  ) :   1.67204463    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   2.96977305    
 
```

Based on these numbers, I think it remains desirable to expose subroutine versions of `diff` (even just rank-1 inflexible versions). Unless there is another good way to make up for the factor 2-ish speed penalty. 

FYI I'm travelling soon, until late January, so you probably won't hear from me for awhile.

**Comment by gareth-nx** [comment]
@zoziha My previous timings were contaminated by some [compilation issues](https://github.com/fortran-lang/stdlib/issues/614).

But that's now fixed, and I had a go at implementing a subroutine version of `diff` (called `difs`) in stdlib. It includes optional arguments just like the function version (indeed the subroutine body is copied from the latter).

[This gist](https://gist.github.com/gareth-nx/cfee7ab78d5c80e4e6e624d9c945fc1a) contains stdlib_math.fypp and stdlib_math_diff.fypp (modified from your second-to-last pull request) with a new subroutine version added, and the test code below. 

The timings below suggest that we get a good speed improvement with the subroutine version (from 20% to 220%). Note that subroutine version is almost as fast as inline code in the case where `append, prepend` are not provided.
```
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.77880740    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.27873874    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.23226142    
 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   3.25370550    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   3.18128562    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.67516923    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   1.69065380    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.68279576    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   1.89143384    

```

To me, this makes it worthwhile to support a subroutine interface. But up to you if you'd like to merge that into the current pull request.

**Comment by jvdp1** [comment]
Thank you @gareth-nx for these interesting tests. If `difs` is integrated in stdlib, should the function call `difs` to avoid duplicated implementations?
Also, am I right that `difs` is less flexible than the function, since it is the user who must explicitely allocate the output array (note that I don't think it plays on the time/performance)?

**Comment by jvdp1** [comment]
@gareth-nx Note that I tested the previous version with Gfortran 11 on my computer. Strangly, the ratio was about 1 when `append` and `prepend` were provided. But the ratio was 1.5-2 when no append and prepend were provided.

**Comment by gareth-nx** [comment]
@jvdp1 IMO it would make sense to have the function `diff` call `difs` to avoid code duplication, assuming there is not a significant performance hit. 

With `difs` the user must provide an output array of the correct size (`size(x) + size(prepend) + size(append) - n)`). The [implementation in the gist](https://gist.github.com/gareth-nx/cfee7ab78d5c80e4e6e624d9c945fc1a) should throw an error if that doesn't hold.

**Comment by gareth-nx** [comment]
> @gareth-nx Note that I tested the previous version with Gfortran 11 on my computer. Strangly, the ratio was about 1 when `append` and `prepend` were provided. But the ratio was 1.5-2 when no append and prepend were provided.

@jvdp1 - My earlier tests were comparing a "locally provided" implementation vs the stdlib version (I guess this is what you ran?). My results were [distorted by my CMake build options](https://github.com/fortran-lang/stdlib/issues/614). 

However the most recent tests are difference -- they compare `diff` and `difs`, where both are implemented inside stdlib [modified like in this gist](https://gist.github.com/gareth-nx/cfee7ab78d5c80e4e6e624d9c945fc1a). So the recent test is different to the earlier one.

But definitely we should check that you/others also find speed improvements in the subroutine case.

**Comment by jvdp1** [comment]
> I guess this is what you ran?

Yes, it is.

> But definitely we should check that you/others also find speed improvements in the subroutine case.

Here are the results on my computer for your latest proposition:
```
$ gfortran --version
GNU Fortran (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Copyright © 2021 Free Software Foundation, Inc.
Ce logiciel est un logiciel libre; voir les sources pour les conditions de copie.  Il n'y a
AUCUNE GARANTIE, pas même pour la COMMERCIALISATION ni L'ADÉQUATION À UNE TÂCHE PARTICULIÈRE.

$ ./run_test 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.60558581    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.36496305    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           1
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.47273850    
 
 Test case with N=    10000000 ; reps=          10 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   2.59290648    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   2.64394450    
 
 Test case with N=       10000 ; reps=       10000 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.75855780    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   1.55266237    
 
 Test case with N=         100 ; reps=     1000000 ; size_append_prepend=           0
 Time ratio (stdlib_function / stdlib_subroutine  ) :   1.46825039    
 Time ratio (stdlib_function / inline_without_append_prepend_or_n  ) :   1.66346598    
 
```

Strange thing: the ratios are higher when no prepend/append are present.

Also, why is the output arrray not allocatable in the subroutine? This would add flexibility for the user IMO.

**Comment by gareth-nx** [comment]
@jvdp1 I'm not surprised that the ratios are higher without `prepend/append`. When `prepend/append` are provided, both the subroutine and function versions create a work array (which presumably takes some time), while the function version also allocates its output (not required with the subroutine). However when `prepend/append` are not provided, there is no need for a work array. Hence in terms of memory demands, the difference between the function/subroutine versions will be relatively greater in that case.

I did not make the subroutine output array allocatable, simply because I assumed that would lead to greater speed. But I haven't checked that.

But there is another reason to make it not allocatable. We might apply the subroutine to arrays that cannot be allocatable (e.g. some sub-array of a larger array, like y(2:99, 3, 4), which we cannot sensibly reallocate). On the other hand, in situations where  we want the benefits of automatic allocation, the function version is good for that.

**Comment by jvdp1** [comment]
> @jvdp1 I'm not surprised that the ratios are higher without `prepend/append`. When `prepend/append` are provided, both the subroutine and function versions create a work array (which presumably takes some time), while the function version also allocates its output (not required with the subroutine). However when `prepend/append` are not provided, there is no need for a work array. Hence in terms of memory demands, the difference between the function/subroutine versions will be relatively greater in that case.

Indeed, it makes sense.

> But there is another reason to make it "not allocatable". We might apply the subroutine to arrays that cannot be allocatable (e.g. some sub-array of a larger array, like y(2:99, 3, 4), which we cannot sensibly reallocate). On the other hand, in situations where we want the benefits of automatic (re)allocation, and do not mind the speed penalty, the function version is good for that.

This is indeed an important reason I didn't think about. Thanks for the explanation. With all these explanations, I am in favour of having both.
