### ISSUE TITLE
gauss_legendre with interval

### ISSUE THREAD

**Issue by mjben** [fortran-lang/stdlib#619]
### Description

Unless I missed something, there should not be x(1) = interval(1) and x(size(x)) = interval(2) in gauss_legendre subroutines, this would only be relevant for gauss_legendre_lobatto.

### Expected Behaviour

gauss_legendre(x, w, interval=[-1._dp, 1._dp]  should give same result as without interval optional.

### Version of stdlib

0.1.0

### Platform and Architecture

Linux

**Comment by ivan-pi** [comment]
@hsnyder, can you comment on this issue?

The classic Gauss-Legendre quadrature indeed doesn't have nodes at the interval endpoints.

**Comment by hsnyder** [comment]
mjben is correct, this is an error. Feel free to fix it if either of you want to, otherwise I will can do so over the weekend.

**Comment by jvdp1** [comment]
> mjben is correct, this is an error. Feel free to fix it if either of you want to, otherwise I will can do so over the weekend.

Has this bug been fixed?

**Comment by hsnyder** [comment]
I've opened a pull request to fix this issue. Sorry for the delay!
