### ISSUE TITLE
stdlib topics

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/stdlib#620]
I suggest adding the topics strings, hash, hash-table, numpy, numerical-integration, quadrature, rng, pseudorandom, sort, sorting, statistics, probability-distribution. The down side is that the topic list may look cluttered. The up sides are that users can look at the topics and quickly get an idea of the scope of stdlib and that searches for language:fortran topic:rng (for example) will bring up stdlib.

**Comment by awvwgk** [comment]
Added more topics

**Comment by Beliavsky** [comment]
Another topic I suggest adding is `numerical-methods`, which has 1395 hits, 50 Fortran-specific.

**Comment by Beliavsky** [comment]
Since the project has fpm build instructions I suggest adding the topic `fortran-package-manager`.
