### ISSUE TITLE
text file fortran90 compiler in the Xshell

### ISSUE THREAD

**Issue by hkch01** [fortran-lang/stdlib#623]
Hi,
I have been using PG fortran90 in Unix for some days. Lately when I am running a program I get the following error message

PGFIO-F-225/list-directed read/unit=10/lexical error-- unknown token type.
File name = /TB/88102/88102_2020083112.txt formatted, sequential access record = 6
In source file test4.f90, at line number 27

I spent many days printing out the problem. I need help from the forum

So I want to ask you a question this time.
First of all, I made up the code recklessly, but there are many useless parts.

I’d like to do a fortran90 compiler of the file
‘/TB/88102/88102_2020083112.txt’.

The structure of this text file…
There are 12 columns and 6,812 rows.

I want to make it the simplest in this language.

Please tell me the code that you print out.

Thanks
Tomas

**Comment by awvwgk** [comment]
@hkch01 This issue is not really related to the Fortran standard library, is it? Maybe you can reach a larger audience by posting your question in the [Fortran-lang discourse](https://fortran-lang.discourse.group/).

Closing this issue for now.
