### ISSUE TITLE
Position independent code

### ISSUE THREAD

**Issue by kjelljorner** [fortran-lang/stdlib#644]
I came across an issue with statically linking stdlib as a dependency for a shared library target. In the end, I [solved](https://github.com/kjelljorner/libconeangle/blob/c81430584225e76b3673176ffdca7e5050151931/CMakeLists.txt#L27) it by setting the `POSITION_INDEPENDENT_CODE` property for the `fortran_stdlib` target:

```cmake
set_target_properties(fortran_stdlib PROPERTIES POSITION_INDEPENDENT_CODE ON)
```

One idea would be to always set this property, but as I understand this could also lead to performance issues.

**Comment by awvwgk** [comment]
I don't see an issue with setting this property by default for stdlib. Feel free to open a PR to propose such change.
