### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by JonathanKipp** [fortran-lang/stdlib#661]
### Description

compiler: any of gcc10,gcc12
OS: linux-gnu
>>>uname -a
Linux iff1426 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 20:59:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Following the instructions from README, I get a lot of failing tests when doing ```cmake --build build --target test``` (see attached file).
I ran the tests and installed succesfully on the same platform with the same compilers before i did a new ```git pull```, but I dont remember if it was another release.

[LastTest.log](https://github.com/fortran-lang/stdlib/files/8821642/LastTest.log)

### Expected Behaviour

I expect the tests to run succesfully.

### Version of stdlib

any from 8e0d8dd down to fb4ca801f0c8e0ed09f9d137c620676fa348ebdd

### Platform and Architecture

OS: linux-gnu >>>uname -a Linux iff1426 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 20:59:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 14NGiestas** [comment]
Thank you for reporting (and sorry by the 1mo delay).
I'm not being able to reproduce the error at all.

In your log there is a lot of version GFORTRAN_10 not found which probably means something is wrong with your dynamic linker not being able to find the correct libgfortran (it's the system fault).

Could you tell more about what distro are you using? Is it a WSL?
Also could you please post the results of the following commands:

```sh
locate libgfortran
echo $LD_LIBRARY_PATH
echo $LD_PRELOAD
```

**Comment by JonathanKipp** [comment]
Dear Ian,

Thank you for responding. I have run the commands you asked, the output is pasted below.
About the system: I have pasted the content of ~/etc/os-release also below.


------------------------
~/etc/os-release:
------------------------
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION=“8"

------------------------
echo $LD_LIBRARY_PATH
------------------------
/tmp_mnt/el8/intel/compilers_and_libraries_2020.0.166/linux/mpi/intel64/libfabric/lib:/tmp_mnt/el8/intel/compilers_and_libraries_2020.0.166/linux/mpi/intel64/lib/release:/tmp_mnt/el8/intel/compilers_and_libraries_2020.0.166/linux/mpi/intel64/lib:/usr/local/lib/vtk:/usr/local/wx/lib:/usr/local/dshome/lib:/usr/local/dshome/local/tacoclntlib:/usr/local/extras/intel/lib

------------------------
echo $LD_PRELOAD
------------------------
There is no output in the shell. This variable seems to be empty.

Kind regards,
Jonathan Kipp
PhD Candidate

Topological Nanoelectronics Group
PGI-1/IAS-1, Juelich Research Center

https://www.fz-juelich.de/pgi/pgi-1/EN/Home/home_node.html

***@***.***

**Comment by Romendakil** [comment]
This really looks like - as was mentioned above - that the paths on your system have been changed during your building change. /lib64 does not look like a standard place where a libgfortran.so resides on a Linux system. On RedHat or Scientific Linux they reside in /usr/lib64, for Ubuntu it is in /usr/lib/x86_64-linux-gnu. Could it be that some variable that was at the head of /lib64 is missing? In any case the error message tells that the gfortran 10 version is not available/compatible with the libgfortran.so as you can see e.g. from this page: https://www.mjr19.org.uk/sw/gfortran.html

**Comment by 14NGiestas** [comment]
@JonathanKipp, you forgot to include the output of `locate libgfortran.so` (this one is really important).

Here is the output on my machine (Arch Linux):
```
/usr/lib/libgfortran.so
/usr/lib/libgfortran.so.5
/usr/lib/libgfortran.so.5.0.0
/usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/libgfortran.so
/usr/lib32/libgfortran.so
/usr/lib32/libgfortran.so.5
/usr/lib32/libgfortran.so.5.0.0
```

Pick one of the lines of the `locate` command in your machine and do (as pointed out by @Romendakil):

`$ strings -a <a entry result of locate.so> | grep '^GFORTRAN_[0-9]'`

Here is the output on my machine:
```
$ strings -a /usr/lib/libgfortran.so.5 | grep '^GFORTRAN_[0-9]'
GFORTRAN_8
GFORTRAN_9
GFORTRAN_9.2
GFORTRAN_10
GFORTRAN_10.2
GFORTRAN_12
GFORTRAN_8
GFORTRAN_10
GFORTRAN_10.2
GFORTRAN_9
GFORTRAN_9.2
GFORTRAN_12
```

As you can see  the GFORTRAN_10 abi is supported here.

If you found the GFORTRAN_10 in any of the entries then try running it with appending a `LD_LIBRARY_PATH=<path to that library> <the usual build commands>`.
Otherwise, it means no libgfortran.so provides the GFORTRAN_10 ABI in which case you will need to report it to your distro, this is a bug.

If none of this helped, I suggest you fetch a fresh copy of the code (to avoid any possible conflict with build files like older "mod" files) and try again.

**Comment by JonathanKipp** [comment]
@14NGiestas Sorry, I forgot about the libgfortran. As you can see below, your and @Romendakil are right:
'''
strings -a /usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgfortran.so | grep '^GFORTRAN_[0-9]'
GFORTRAN_1.0
GFORTRAN_1.1
GFORTRAN_1.2
GFORTRAN_1.3
GFORTRAN_1.4
GFORTRAN_1.5
'''
I will talk to the admins about this, thank you!

**Comment by awvwgk** [comment]
> `/usr/lib/gcc/x86_64-redhat-linux/4.8.2/libgfortran.so`

GFortran 4.8 is missing features used in stdlib, you need at least GFortran 9 or newer.

**Comment by 14NGiestas** [comment]
Hi @JonathanKipp, your LD_LIBRARY_PATH should be a path-to-a-folder not a path-to-a-file, you should try this instead:

```
LD_LIBRARY_PATH="/usr/local/gcc10/lib64/" cmake -B build -DCMAKE_INSTALL_PREFIX="${HOME}/.local/stdlib_gnu"
LD_LIBRARY_PATH="/usr/local/gcc10/lib64/" cmake --build build -j 4
LD_LIBRARY_PATH="/usr/local/gcc10/lib64/" cmake --build build --target test
```

This way you may be able to compile and test the stdlib in your system's current state, but you should look for a permanent solution.

**Comment by IngoMeyer441** [comment]
I also tried to run the tests in @JonathanKipp's working environment. Setting `LD_LIBRARY_PATH="/usr/local/gcc10/lib64/"` indeed works. However, we will alter the compiler setup to reference its `libgfortran.so` by an absolute path, so setting environment variables won't be necessary in the future. Thanks for your help!
