### ISSUE TITLE
Determine the FORD version number for FORD CI document deployment

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/stdlib#673]
### Motivation

As far as I know, in both [#624](https://github.com/fortran-lang/stdlib/pull/624#issuecomment-1030510430) and [#278](https://github.com/fortran-lang/stdlib/pull/278), the failure of FORD document deployment occurs, which is often caused by the features and version updates of FORD.
Determining the appropriate FORD version for stdlib in stages will help new contributors are less likely to face FORD CI failures due to FORD version updates.

### Prior Art

https://github.com/fortran-lang/stdlib/blob/c6b54e1eee1be10ea144b430a673e20b843f50de/.github/workflows/doc-deployment.yml#L37

We can use:

```sh
pip install -v ford==6.1.10
```

### Additional Information

- https://github.com/Fortran-FOSS-Programmers/ford/issues/446

**Comment by awvwgk** [comment]
There is some historical baggage on the documentation workflow, see https://github.com/fortran-lang/stdlib/issues/289. It might be time to revisit the workflow and use a different setup strategy.

**Comment by zoziha** [comment]
Currently stdlib publishes FORD documents based on macOS and brew, while fpm publishes FORD documents based on Ubuntu and pip, it seems to use pip to install ford and publish docs is easier, maybe we can update stdlib's docs CI with [fpm's CI](https://github.com/fortran-lang/fpm/blob/1a8a96be600cc9f0bf99ec7a1c2aa710e889c0bb/.github/workflows/docs.yml#L1).

**Comment by jvdp1** [comment]
I think it makes sense to use the same strategy in all Fortran-lang projects regarding `ford`.
@zoziha  would you like to open a PR with a new strategy?
