### ISSUE TITLE
How can i use Fortran libraries for Code::Blocks IDE

### ISSUE THREAD

**Issue by MehmetSolak** [fortran-lang/stdlib#682]
So sorry, total beginner here.
May I ask how I can use, for example, the stat module of FORTRAN with Code::Blocks IDE?
Thanks.

**Comment by Euler-37** [comment]
1. Stdlib only supports gfortran 9+ , and code::block 20.03 just has gfortran 8.1,so you should download new gfortran compiler.   [equation.com](http://www.equation.com/servlet/equation.cmd?fa=fortran)

2. It is easy to build it if using `fpm` [fpm](https://github.com/fortran-lang/fpm),and must install `git`.

3. Using powershell build it . 
``` sh
git clone https://github.com/fortran-lang/stdlib
cd stdlib
git checkout stdlib-fpm
fpm build --profile release
```
4. copy lib
        - copy  all `.mod` and `.smod` files from `your path/stdlib/build/gfortran_XXXXXXXX/`  to **YOUR** gfortran directory,for example `D:/software/gcc/include`. 
        - copy `libstdlib.a` from `your path/stdlib/build/gfortran_XXXXXXXX/stdlib/` to `D:/software/gcc/lib`
5.  open code::blocks, config `Settings->Compiler`
       -  ` ->linker setting -> other linker options` ,add `-lstdlib`
       -  `-> search  directories-> compiler ` ,click  `add` and choose include directory ,for example `D:/software/gcc/include`
 
DONE

**Comment by Euler-37** [comment]
> Thank you for your answer Euler-37. Thank you so much. For now, I have failed but I will keep searching. I have made 3 steps, but in the step 4 I can not find where my gfortran directory is. When I search
> 
> ```
> which gfortran
> /usr/bin/gfortran
> ```
> 
> but I can not find where the ""D:/software/gcc/lib"" is and where to copy the files.

so your pc is  linux or windows/msys2
