### ISSUE TITLE
failed tests

### ISSUE THREAD

**Issue by masoudshao** [fortran-lang/stdlib#684]
The following tests did not run:
	  1 - always_skip (Skipped)
	100 - check4 (Skipped)

`$ gfortran --version`
GNU Fortran (Homebrew GCC 11.3.0_1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.

`$ clang --version ### CXX compiler`
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix

macOS Big Sur

`$ uname -pa`
version 11.6.1 (20G224)
Darwin S31-37KHML7H 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
i386

**Comment by masoudshao** [comment]
built with 

`export FFLAGS="-O3"`

`cmake -B build -G Ninja -DCMAKE_MAXIMUM_RANK:String=7 -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_VERBOSE_MAKEFILE=On -DCMAKE_BUILD_TYPE=NoConfig`

**Comment by ivan-pi** [comment]
I believe those tests are supposed to be skipped.

Both are marked with the [`SKIP_RETURN_CODE`](https://cmake.org/cmake/help/latest/prop_test/SKIP_RETURN_CODE.html) property.

```
set_tests_properties(always_skip PROPERTIES SKIP_RETURN_CODE 77)
```
