### ISSUE TITLE
gcc-9 build on macos-latest fails

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#696]
### Description

See this job https://github.com/fortran-lang/stdlib/actions/runs/4235861778/jobs/7360686209

and specifically the error message from the CMake compiler tester: https://github.com/fortran-lang/stdlib/actions/runs/4235861778/jobs/7360686209#step:7:30

From the previous step, it looks like gfortran-9 is installed successfully via brew, however, I wonder if this link-time breakage is related to updates to the recent `macos-latest` change from v11 to v12 (https://github.com/actions/runner-images/issues/6384) I don't have any experience with macOS so it's not obvious to me what exactly causes the issue here.

Possible solutions:

* A macOS expert in the community can identify why gfortran-9 is not linking correctly and apply a fix;
* We remove gfortran-9 from the matrix for macOS.

To reduce complexity in the future, we could also remove the brew install step and only rely on GH Action supported compiler versions. On the current `macos-latest` (macOS 12), that's gfortran 11 and 12.

What do you think? I'm personally in favor of simply relying on the GitHub Actions provided compiler versions. For this specific issue, it would mean removing gfortran-9 from the matrix for macOS.

### Expected Behaviour

CI should succeed.

### Version of stdlib

fba31e0db6375e9207438d2815b8552dc87c6f0b

### Platform and Architecture

macos-latest (macos-12)

**Comment by barracuda156** [comment]
@milancurcic I am not an expert on fortran, but IMO the only GCC it makes sense to support besides the current one is GCC 10 (because it is the last version to be bootstrapped without C++11). Maybe GCC 7, since it has been and presently is the main compiler on older macOS in Macports (but I hope we move to GCC 12 soon). There is no special utility in GCC 9 on MacOS, AFAICT.
