### ISSUE TITLE
The first step in facilitating BLAS integration into stdlib: add a solve function

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/stdlib#709]
### Motivation

Fortran arrays have a natural advantage in linear algebra, but unfortunately, stdlib currently does not integrate any high-level function implementation based on BLAS, LAPACK interfaces, such as `det`, `solve`, `inv`. For Fortran users, this is frustrating. Obviously we can use LAPACK directly, but stdlib's motivation is to be the math library that can catch up with `numpy`, and linear algebra is essential.
(I understand that this may not be a purely technical issue, it may involve consensus and norms.)

I'd like to start by trying to link `openblas` in stdlib (`numpy` gives preference to `openblas` and `mkl`) and show you that we are enthusiastic about BLAS. Maybe it won't succeed directly, but I'll still try to implement `linalg.solve` like `numpy`.

`solve` is not computationally efficient: There are two array assignments before `_gesv` is called, which takes a bit of time for large arrays, but is good for ease of use.
Also, since this is the first time LAPACK is encapsulated, there is no assertion on the return value `info`, so discussion is welcome.

### Prior Art

- [numpy.linalg.solve](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html)
- [scipy.linalg.solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve)

**Comment by jvdp1** [comment]
Related to #749
