### ISSUE TITLE
Adding a procedure getting all keys in the hashmaps

### ISSUE THREAD

**Issue by degawa** [fortran-lang/stdlib#732]
### Motivation

The hashmap in the stdlib does not provide a way to retrieve all keys in the map. As shown in the Prior Art section, a way to retrieve all keys in a hashmap is required in other programming languages, and it would significantly expands the use of the hashmap.

### Prior Art

The [Map](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html) in Java has the `SetKey()` method that returns the keys in this map.
The `list()` function for [Python's `dict`](https://docs.python.org/3/library/stdtypes.html#typesmapping) returns a list of all the keys used in the dictionary.
The `unordered_map` in C++ does not have a similar method, but a way to get all the keys is required. (for example, see https://stackoverflow.com/questions/8483985/obtaining-list-of-keys-and-values-from-unordered-map)

### Additional Information

The hashmaps in the stdlib, including `open_hash_map_type` and `chaining_hash_map_type`, store both the entered keys and values to the component `inverse`. So it is not challenging work to retrieve the keys as a `key_type` array. 
The conversion from the `key_type` to the original type is left to the users.

**Comment by awvwgk** [comment]
In TOML Fortran the map types support returning a list of keys, which can be used to iterate through the data structure. In general using stdlib' s map type in TOML Fortran requires this functionality, and one way of implementing this would be to just store the keys in a list beside the map.

**Comment by jvdp1** [comment]
Thank you @degawa for the proposal.

>The hashmaps in the stdlib, including open_hash_map_type and chaining_hash_map_type, store both the entered keys and values to the component inverse. So it is not challenging work to retrieve the keys as a key_type array.

It seems you already have an idea on how to implement such an option. Would you like to open a PR for its implemenation?
