### ISSUE TITLE
test fault by string_intrisic

### ISSUE THREAD

**Issue by nkevy** [fortran-lang/stdlib#735]
### Description

Test No. 45 string_intrinsic faults on
`ctest --test-dir build/test --rerun-failed --output-on-failure`
Here is the relevant output
`45/60 Test #45: string_intrinsic .................Subprocess aborted***Exception:   0.01 sec
# Testing: string-intrinsic
  Starting lgt ... (1/17)
       ... lgt [PASSED]
  Starting llt ... (2/17)
       ... llt [PASSED]
  Starting lge ... (3/17)
       ... lge [PASSED]
  Starting lle ... (4/17)
       ... lle [PASSED]
  Starting trim ... (5/17)
       ... trim [PASSED]
  Starting len ... (6/17)
       ... len [PASSED]
  Starting len_trim ... (7/17)
       ... len_trim [PASSED]
  Starting adjustl ... (8/17)
       ... adjustl [PASSED]
  Starting adjustr ... (9/17)
       ... adjustr [PASSED]
  Starting scan ... (10/17)
       ... scan [PASSED]
  Starting verify ... (11/17)
       ... verify [PASSED]
  Starting repeat ... (12/17)
       ... repeat [PASSED]
  Starting index ... (13/17)
       ... index [PASSED]
  Starting char ... (14/17)
       ... char [PASSED]
  Starting ichar ... (15/17)
       ... ichar [PASSED]
  Starting iachar ... (16/17)
       ... iachar [PASSED]
  Starting move ... (17/17)

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x10ab0fafe
#1  0x10ab0ecdd
#2  0x7fff207a3d7c`

The getting started document asks nicely for reports about faults found while getting started. So, here it is.
Kind Regards,
Noah

### Expected Behaviour

`tart 45: string_intrinsic
45/60 Test #46: string_intrinsic .....................   Passed    0.00 sec`

### Version of stdlib

Version 0.3.0

### Platform and Architecture

MacOS 11.7.4

### Additional Information

cmake version 3.27.4
Xcode:	13.2.1 (19586)
MacOS 11.7.4

**Comment by jvdp1** [comment]
Thank you for reporting the bug. I believe it is related to #731
