### ISSUE TITLE
Compilation error on Linux. Disabling hash/hashmap files compiles rest of the project successfully.

### ISSUE THREAD

**Issue by aerosayan** [fortran-lang/stdlib#740]
I tried to compile stdlib, bu the hashmap code is throwing compilation errors.

I disabled all the code for hash/hashmap, and the rest of the project compiles correctly, so most likely there's so issue only in the hash/hashmap code in file `stdlib_hashmap_open.f90`.

- Cmake worked correctly.
- Fypp worked correctly to generate the files
- Most of the compilation and linking worked correctly.
- Only issue is in hashmap code.

The initial error I got for the hashmap code was in `stdlib_hashmap_open.f90`:

```
 Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_hashmap_open.f90.o
/home/mypc/code/stdlib/src/stdlib_hashmap_open.f90:10:25:

   10 | submodule(stdlib_hashmaps) stdlib_hashmap_open
      |                         1
......
   13 |         character_storage_size,              &
      |                              2
Error: Symbol ‘character_storage_size’ at (1) conflicts with the symbol at (2)
make[2]: *** [src/CMakeFiles/fortran_stdlib.dir/build.make:367: src/CMakeFiles/fortran_stdlib.dir/stdlib_hashmap_open.f90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2418: src/CMakeFiles/fortran_stdlib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

Kindly Note: I'm **not** implying that there's any issue with all of the hash or hashmap files that I have disabled from the CMake files. The main issue is only with the `stdlib_hashmap_open.f90` file. I just disabled the rest of the files to test how much of the project compiles successfully.

The disabled files are:

```
file: src/CMakeLists.txt
-    stdlib_hash_32bit.fypp 
-    stdlib_hash_32bit_fnv.fypp
-    stdlib_hash_32bit_nm.fypp 
-    stdlib_hash_32bit_water.fypp 
-    stdlib_hash_64bit.fypp 
-    stdlib_hash_64bit_fnv.fypp 
-    stdlib_hash_64bit_pengy.fypp 
-    stdlib_hash_64bit_spookyv2.fypp 
-    stdlib_hashmap_wrappers.f90
-    stdlib_hashmaps.f90
-    stdlib_hashmap_chaining.f90
-    stdlib_hashmap_open.f90

file: example/CMakeLists.txt
-add_subdirectory(hashmaps)
-add_subdirectory(hash_procedures)

file: test/CMakeLists.txt
-add_subdirectory(hash_functions)
-add_subdirectory(hash_functions_perf)
-add_subdirectory(hashmaps)
```

System information.

- Linux, Ubuntu 20.04.1 LTS
- cmake automatically selects `/usr/bin/f95` as the compiler for all of the files, as seen in the verbose make output.
```
[ 10%] Building Fortran object src/CMakeFiles/fortran_stdlib.dir/stdlib_io.f90.o
cd /home/mypc/code/stdlib/build/src && /usr/bin/f95  -I/home/mypc/code/stdlib/build/src/mod_files  -fimplicit-none -ffree-line-length-132 -O2 -g -DNDEBUG -Jmod_files/ -fPIC   -fno-range-check -c /home/mypc/code/stdlib/build/src/stdlib_io.f90 -o CMakeFiles/fortran_stdlib.dir/stdlib_io.f90.o
```

**Comment by jvdp1** [comment]
Thank you for reporting the bug. Which version of compiler do you use?

**Comment by aerosayan** [comment]
Okay, so `/usr/bin/f95` seems to be gfortran behind the scenes, and the version is 9.3.0.

```
$ /usr/bin/f95 --version
GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by aerosayan** [comment]
I did some more testing.

I enabled and compiled all of the files in the src/ folder except `stdlib_hashmap_open.f90` and all of them compile perfectly.

So, the only issue seems to be in `stdlib_hashmap_open.f90`

Also, I compiled the _complete stdlib repo_ with Intel ifort (2021.5.0 20211109), including the file `stdlib_hashmap_open.f90` and all of the test files, and did _not_ face any compilation errors. 

The issue seems to be only with gfortran 9.3.0.

Thanks

**Comment by Romendakil** [comment]
This is a (temporary) regression in gfortran which appears only (to my knowledge in the version 9.3.0:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92736
9.2.0 still worked ok, it was introduced for 9.3.0 but fixed for 9.4.0. I believe the initial release 10.1.0 was free from that regression. The conflict comes from the statement 
`use <module_name>, only: <var_name>` in both module and submodule, here for the iso_fortran_env intrinsic module. You either have to tolerate this failure or solve it by removing one of the use statements or to remove the `only` statements.

**Comment by jvdp1** [comment]
Thank you for the explanations.
Your can find [here](https://github.com/fortran-lang/stdlib/blob/d379587a760376e5663ffe47b10425912faf32c2/README.md?plain=1#L86) a list of compilers that can compile (or not) `stdlib`. gfortran 9.3.0 seems to work on Windows. Could you maybe report your issue in this list, please?

**Comment by aerosayan** [comment]
Hi, I don't use those versions of compilers named in your list.

I think since this was a regression bug, and GNU backported the fix, it should be okay for other users.

I don't have anything else to add.

You can close the issue.

Thanks.
