### ISSUE TITLE
Add `.gitignore` to `stdlib-fpm` deployment for generated test files

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/stdlib#766]
### Motivation

A number of `.txt`,`.bin`, `.dat` and `.stream` files are created when running tests with `fpm test` on the `stdlib-fpm` branch. However, a `.gitignore` file is missing so the files end up cluttering the `git diff` and need to be manually deleted every time. While most of the development work will be done from the `master` branch, I think it is useful to be able to switch to the `stdlib-fpm` branch to try things out.

### Prior Art

There is a `.gitignore` file on the `master`(branch name also needs change?) branch so some entries can be copied over during deployment.

### Additional Information

I believe it would be more advantageous to avoid placing any files generated by tests directly in the project's root directory. Instead, they could be stored, for instance, in a `build/test` or `tmp/test` folder (open for suggestions). However, I acknowledge that for the time being, adding a `.gitignore` file is the simplest solution.

**Comment by perazz** [comment]
The `stdlib-fpm` is generated on deployment @minhqdao, please check back the details at https://github.com/fortran-lang/stdlib/blob/master/ci/fpm-deployment.sh
