### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/stdlib#8]
What should we use for continuous integration? 

GitLab's CI tools are amazing, but on GitHub I struggle every time I want to set up something. What's the state-of-the-art here for a Fortran+C project, ideally with builds for as many platforms we can get, and ideally free of charge?

@zbeekman @jacobwilliams @scivision

We have some time to explore and decide, but at the point when we have some code + tests in, we should CI.

**Comment by zbeekman** [comment]
My vote is for a combination of Github Actions and CircleCI. If we want/need exotic hardware, I have some aarch64 machines that we could host self-hosted github actions builders or gitlab-ci workers on. Docker can emulate other arches too, and I may be able to convince some folks at University of Oregon to allow access to dockerized test runners on things like Xeon Phi, and NEC VE, PPC, etc.

I've recently really been enjoying using [pipenv](https://pipenv.readthedocs.io/en/latest/) to manage some additional tools and the build-run environment. I install the latest CMake this way, as well as [Jin2For](https://gitlab.com/fverdugo/jin2for) and [pre-commit](https://pre-commit.com/) hooks that way in [ZstdFortranLib](https://github.com/zbeekman/ZstdFortranLib).

I'd be happy to help implement CI&build stuff. And I'd love to be part of the GH org.

**Comment by scivision** [comment]
In the past year Travis-CI added ARM and IBM POWER arch. It seems after a dry spell there is a renewed interest in Travis development. Generally I have good success with GitHub actions as a primary choice.

**Comment by zbeekman** [comment]
Oh, wow! I left Travis-CI for dead after getting too frustrated with it. I'll have to go take another look. Is the ARM and IBM POWER documented?

**Comment by scivision** [comment]
https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z

**Comment by ivan-pi** [comment]
I have a simple Travis script (only for gfortran) that works for MacOS (with brew) and Linux in my Fortran interface for METIS: https://github.com/ivan-pi/fmetis/blob/master/.travis.yml
The script is is very similar to the Github-CI.

**Comment by zbeekman** [comment]
We could add Travis. I'm not sure there's a compelling need, unless we want to test ARM/power, etc. archs

**Comment by certik** [comment]
@ivan-pi thanks. As @zbeekman said, we can add Travis (and Appveyor and Azure Pipelines or CircleCI). The main advantage of GitHub Actions is that the Windows, macOS and Linux configuration is uniform, in the single configure file:

https://github.com/fortran-lang/stdlib/blob/c6b81196d495884558e653aae064f4d8781c0a96/.github/workflows/main.yml

and it seems (at least so far) quick to run.
