### ISSUE TITLE
Extend `sort_index` interface to allow `int32` index argument

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/stdlib#822]
The `index` argument of `sort_index` has type `int64`. I suggest that the `sort_index` interface be extended so that an `index` argument of type `int32` is also supported. I understand that `int64` was chosen to accommodate very large arrays, but it in most cases `int32` is sufficient, and many programmers use default integers. The current interface trips people up, for example [here](https://fortran-lang.discourse.group/t/error-there-is-no-specific-subroutine-for-the-generic-sort-index/1728/9) and [here](https://github.com/fortran-lang/stdlib/issues/719).

**Comment by jvdp1** [comment]
thank you @Beliavsky for the heads up. Indeed, having both version could be useful.
I will have a look.
