### ISSUE TITLE
macos-12 builds failing again

### ISSUE THREAD

**Issue by jalvesz** [fortran-lang/stdlib#831]
### Description

The macos-12 cmake build is failing

### Expected Behaviour

Not fail

### Version of stdlib

0.6.1

### Platform and Architecture

macos

### Additional Information

the failed build log can be seen for instance here https://github.com/fortran-lang/stdlib/actions/runs/9331866687/job/25687032018?pr=821 other PRs have the same symptom. It doesn't seem to be related to the PR itself.

**Comment by jvdp1** [comment]
It seems to be related to `gcc` itself. Restarting them fix them sometimes.
