### ISSUE TITLE
Should installation set include paths specifying GCC (gfortran) version?

### ISSUE THREAD

**Issue by barracuda156** [fortran-lang/stdlib#846]
I just noticed that installation sets paths in a form of `${chosen_prefix}/fortran_stdlib/GNU-13.3.0/` (as an example with the build using gcc13 13.3.0). Is this a) expected behavior and b) actually needed?

The issue is that we have multiple versions of GCC in MacPorts, but `fortran-stdlib` port just sets `+gfortran` variant, which is equivalent to using whichever GCC is used as a primary runtime supplier. So we end up with different pre-built tarballs having identical variants, which is obviously wrong.

If it does matter which exactly `gfortran` version is used, then we (in MacPorts) should change default variant to a specific GCC, plus we will have to revbump the port for every GCC minor version update, since that will also change.
If it does not matter which `gfortran` is used, then paths should be changed in a way to have them compatible across GCC versions, dropping `GNU-${version}` part altogether (whether locally in MacPorts or here in upstream).

**Comment by barracuda156** [comment]
@perazz Could you please comment on this one? I just need to know what to do on our side at least.

**Comment by perazz** [comment]
@barracuda156 not an expert in the stdlib build process. But, I see that Fortran `.mod` files are put in a compiler-named directory:

https://github.com/fortran-lang/stdlib/blob/4859081791fced582f3ca7b48a0c2235cc5c4845/config/CMakeLists.txt#L6

Makes sense to me, because modules are specific to compiler vendor and version. So yes I understand you may end up with many different folders but the same files (if gfortran hasn't changed its module format), but I would refrain from changing this logic because I think it's the safest one?

**Comment by barracuda156** [comment]
@perazz Sure, I just wanted to make sure it is justified.

Perhaps we may not need parallel installations of several versions, but I will require a specific gcc variant to be required (and not a generic gfortran).

**Comment by perazz** [comment]
Yes I think that is the way to go. Otherwise, you should find a way in MacPorts to label the current Fortran compiler version like [CMake](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_VERSION.html) does: 

```
major[.minor[.patch[.tweak]]]
```

**Comment by barracuda156** [comment]
MacPorts can install a fortran-using port either as `+gfortran` (which would translate to whichever gfortran being supplied by the primary gcc version, typically the last release at a given moment) or as `+gccX` (i.e., +gcc14 or whichever specific version is being used). Looks like we just need the second option here, though we will still need to do revbumps on minor versions change.
