### ISSUE TITLE
CI fails trying to install `pip` package on `msys2`

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/stdlib#853]
### Description

An error recently appeared while trying to install `fypp` using `pip` on `msys2`. The [CI fails](https://github.com/fortran-lang/stdlib/actions/runs/10178599692/job/28152543155?pr=760) with the following error message:

```
Run pip install fypp
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-MSYS2-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
```

### Expected Behaviour

`fypp` is installed without failing.

### Version of stdlib

master

### Platform and Architecture

Windows-MSYS2

**Comment by zoziha** [comment]
@minhqdao, this seems to be caused by changes in `Python` and `Pip`. If we insist on using the system-level installation, we can pass the `--break-system-packages` parameter, such as:
```sh
pip install --break-system-packages fypp
```

Or use the virtual environment `venv`:
```sh
python3 -m venv path/to/venv
source <venv>/bin/activate
pip install fypp
```

**Comment by minhqdao** [comment]
That's correct. And if we take the `venv` route, we'd also need to make sure the `venv` is properly `source`d for every subsequent `run`.

But as you pointed out in https://github.com/fortran-lang/stdlib/pull/854#issuecomment-2267405530, it's probably alright to abandon `msystem: msys` altogether. I'll merge the PR so the CI stops failing.
