### ISSUE TITLE
CI running twice, doesn't `on: [push]` suffice?

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/stdlib#856]
All the tests are currently being ran twice, which takes quite a lot of time (and resources). What's the reason behind running the CI both `on: [push, pull_request]`? Wouldn't `on: [push]` suffice?

**Comment by awvwgk** [comment]
The CI should not run twice if you use a fork for making a PR. Please don't push any feature branches to the fortran-lang repo.
